### ISSUE TITLE
Auto whitelist

### ISSUE THREAD

**Issue by jjxtra** [DigitalRuby/IPBan#100]
A user suggested an auto whitelist option where a successful login would whitelist the ip for some specified period.

**Comment by zecman** [comment]
I do not see any benefit of this feature. Some kind of reputation system for IPs?

Most of us have dynamic IP addresses while on the road. When working from the office or via VPN you have one of the private subnets.

Maybe just whitelist all possible pivate IP ranges? > [more info](https://en.wikipedia.org/wiki/Private_network)
