### ISSUE TITLE
Adding ban ip list manually

### ISSUE THREAD

**Issue by aloksharma1** [DigitalRuby/IPBan#102]
Hello,
i am using mailenable and i have extracted malicious ip list from its log files, i want to add this simple txt list to ip ban to process them in banned list : 
sample
141.98.80.61
187.120.159.11

etc just line breaks after each ip, how to do that?

**Comment by jjxtra** [comment]
IPBan can read the mail enable log file directly, that is probably easiest. See DigitalRuby.IPBan.dll.config for some examples.

**Comment by aloksharma1** [comment]
ok,

then what do you suggest for congiguring the log file which is like this?
```
08/25/20 00:00:06	SMTP-IN	D8BB9707D7B14D6790CA19EA25A6FA8C.MAI	8556	212.70.149.36	AUTH	{blank}	334 UGFzc3dvcmQ6	18	26	ds1@maildomain.com	
08/25/20 00:00:07	SMTP-IN	D8BB9707D7B14D6790CA19EA25A6FA8C.MAI	8556	212.70.149.36	AUTH	ZHMxMQ==	535 Invalid Username or Password	34	10	ds1@maildomain.com	
08/25/20 00:00:08	SMTP-IN	CC2FD9F691534CCFA5AEDD78A03DF777.MAI	8640	212.70.149.83			220 mail.maildomain.com ESMTP MailEnable Service, Version: 10.25-- ready at 08/25/20 00:00:08	95	0		
08/25/20 00:00:08	SMTP-IN	D8BB9707D7B14D6790CA19EA25A6FA8C.MAI	8556	212.70.149.36	QUIT	QUIT	221 Service closing transmission channel	42	6	ds1@maildomain.com
```	
08/25/20 00:00:09	SMTP-IN	CC2FD9F691534CCFA5AEDD78A03DF777.MAI	8640	212.70.149.83	EHLO	EHLO User	250-maildomain.com [212.70.149.83], this server offers 5 extensions	239	11		
08/25/20 00:00:11	SMTP-IN	CC2FD9F691534CCFA5AEDD78A03DF777.MAI	8640	212.70.149.83	RSET	RSET	250 Requested mail action okay, completed	43	6		
08/25/20 00:00:12	SMTP-IN	CC2FD9F691534CCFA5AEDD78A03DF777.MAI	8640	212.70.149.83	AUTH	AUTH LOGIN	334 VXNlcm5hbWU6	18	12		
08/25/20 00:00:14	SMTP-IN	CC2FD9F691534CCFA5AEDD78A03DF777.MAI	8640	212.70.149.83	AUTH	{blank}	334 UGFzc3dvcmQ6	18	54	productos.mercadolibre@maildomain.com

**Comment by jjxtra** [comment]
Are all of those failed logins? Do you have an example of success logins? Please feel free to mask ip addresses and user names.

Where are the log files stored by default?

**Comment by aloksharma1** [comment]
yes, those are all failed logins , here i am adding success logins :

```
08/25/20 00:24:52	SMTP-IN	27E8FE49D9C2486EAA481308BF57E7AD.MAI	7068	212.70.149.83	EHLO	EHLO User	250-maildomain.com [212.70.149.83], this server offers 5 extensions	239	11		
08/25/20 00:24:53	SMTP-IN	3A27A6E58240422B90F2DFC24F70E33C.MAI	8636	103.73.35.181	EHLO	EHLO GMPC	250-maildomain.com [103.73.35.181], this server offers 4 extensions	130	11		
08/25/20 00:24:53	SMTP-IN	3A27A6E58240422B90F2DFC24F70E33C.MAI	8636	103.73.35.181	AUTH	AUTH LOGIN	334 VXNlcm5hbWU6	18	12		
08/25/20 00:24:53	SMTP-IN	3A27A6E58240422B90F2DFC24F70E33C.MAI	8636	103.73.35.181	AUTH	{blank}	334 UGFzc3dvcmQ6	18	30	info@maildomain.com	
08/25/20 00:24:53	SMTP-IN	3A27A6E58240422B90F2DFC24F70E33C.MAI	8636	103.73.35.181	AUTH	{blank}	235 Authenticated	19	18	info@maildomain.com	
```

log file path is C:\Program Files (x86)\Mail Enable\Logging\SMTP\SMTP-Activity-200825.log

**Comment by jjxtra** [comment]
Are all the log files of interest in the logging folder and named smtp-activity*.log?

**Comment by aloksharma1** [comment]
yes, all log files are in that pattern

**Comment by jjxtra** [comment]
Add something like this to the `DigitalRuby.IPBan.dll.config` file `LogFiles` section:

```
<!-- Mail enable logins, Windows -->
      <LogFile>

        <Source>MailEnable</Source>
        <PathAndMask>
          C:/Program Files (x86)/Mail Enable/Logging/SMTP/SMTP-Activity*.log
        </PathAndMask>
        <!--
        Example line failure:
        08/25/20 00:00:07	SMTP-IN	D8BB9707D7B14D6790CA19EA25A6FA8C.MAI	8556	212.70.149.36	AUTH	ZHMxMQ==	535 Invalid Username or Password	34	10	ds1@maildomain.com	
        Example line success:
        08/25/20 00:24:53	SMTP-IN	3A27A6E58240422B90F2DFC24F70E33C.MAI	8636	103.73.35.181	AUTH	{blank}	235 Authenticated	19	18	info@maildomain.com	
        -->
        <FailedLoginRegex>
          <![CDATA[
            
          ]]>
        </FailedLoginRegex>
        <SuccessfulLoginRegex>
          <![CDATA[

          ]]>
        </SuccessfulLoginRegex>
        <PlatformRegex>Windows</PlatformRegex>
        <PingInterval>10000</PingInterval>
        <MaxFileSize>16777216</MaxFileSize>

      </LogFile>
```

**Comment by aloksharma1** [comment]
hi,

do i need to restart service after this? or will this be taken care of automatically?

**Comment by jjxtra** [comment]
Service will refresh config every cycle, no need to restart. 

In the above example we just need a regex to pull out the timestamp, ip address, user name.

**Comment by aloksharma1** [comment]
so i need to figure out the regex part for whole line? will try that :)

**Comment by jjxtra** [comment]
Something like this for failed login:
`^(?<timestamp>[0-9] \;)\t[^\t]+\t[^\t]+[\t][^\t]\t(?<ipaddress>[^\t]+)\t[^\t]+\t[^\t]+\t.*?Invalid Username[^\t]+\t[^\t]+\t[^\t]+\t(?<username>[^\t]+)

And success:
`^(?<timestamp>[0-9] \;)\t[^\t]+\t[^\t]+[\t][^\t]\t(?<ipaddress>[^\t]+)\t[^\t]+\t[^\t]+\t.*?235 Authenticated[^\t]+\t[^\t]+\t[^\t]+\t(?<username>[^\t]+)

**Comment by aloksharma1** [comment]
thanks for the head start, i will see if i can correct it and will post working regex here.

**Comment by aloksharma1** [comment]
here are the corrected regex,

`^(?<timestamp>\d{2}\/\d{2}\/\d{2}\s\d{2}:\d{2}:\d{2})+(?<smtp>\t([^,]{49})\t)(?<ipaddress>[^\t]+)\t[^\t]+\t[^\t]+\t.*?Invalid Username[^\t]+\t[^\t]+\t[^\t]+\t(?<username>[^\t]+)`


`^(?<timestamp>\d{2}\/\d{2}\/\d{2}\s\d{2}:\d{2}:\d{2})(?<smtp>\t([^,]{49})\t)(?<ipaddress>[^\t]*)\t[^\t].*?Authenticated\t+[^\t]+\t+[^\t]+\t(?<username>[^\t]+)`


`^(?<timestamp>\d{2}\/\d{2}\/\d{2}\s\d{2}:\d{2}:\d{2})(?<smtp>\t+[^\t]+\t+[^\t]+\t+[^\t]+\t)(?<ipaddress>[^\t]*)\t[^\t].*?Authenticated\t+[^\t]+\t+[^\t]+\t(?<username>[^\t]+)`

`^(?<timestamp>\d{2}\/\d{2}\/\d{2}\s\d{2}:\d{2}:\d{2})(?<smtp>\t+[^\t]+\t+[^\t]+\t+[^\t]+\t)(?<ipaddress>[^\t]*)\t[^\t].*?Invalid Username[^\t]+\t[^\t]+\t[^\t]+\t(?<username>[^\t]+)`

i found a few logs (very rare) which had a different pattern, like this :

`08/25/20 10:47:54	SMTP-IN	A5BF8672904641649F6160728A756FFC.MAI	832	212.70.149.4	AUTH	YnJlZXpl	535 Invalid Username or Password	34	10	breeze@jajoogroup.com	`

is it possible to write multiple regex patterns for same log file?

**Comment by aloksharma1** [comment]
also what about these parameters from other configs in xml?
```
        <PlatformRegex>Windows</PlatformRegex>
        <PingInterval>10000</PingInterval>
        <MaxFileSize>16777216</MaxFileSize>
```

**Comment by aloksharma1** [comment]
here is what i see in ipban logs:

```
08/26/20 03:45:26, source: MailEnable
2020-08-26 03:45:49.9473|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: 183.82.152.35, user name: user@maildomain.com
08/26/20 03:45:31, source: MailEnable
2020-08-26 03:45:49.9673|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: 102.182.3.72, user name: user@maildomain.com
08/26/20 03:45:33, source: MailEnable
2020-08-26 03:45:49.9673|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: 122.173.191.7, user name: user@maildomain.com
08/26/20 03:45:38, source: MailEnable
2020-08-26 03:45:50.0398|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: 45.220.0.147, user name: user@maildomain.com
08/26/20 03:45:39, source: MailEnable
2020-08-26 03:45:50.0617|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: 103.136.156.2, user name: user@maildomain.com
08/26/20 03:45:41, source: MailEnable
2020-08-26 03:45:50.0850|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: 2.50.55.77, user name: user@maildomain.com
08/26/20 03:45:42, source: MailEnable
```

**Comment by jjxtra** [comment]
You can use the | character at the end of a line and start a second regex on the next line.

**Comment by aloksharma1** [comment]
what about the warn logs?

**Comment by jjxtra** [comment]
Can you post an example warning log?

**Comment by aloksharma1** [comment]
> here is what i see in ipban logs:
> 
> ```
> 08/26/20 03:45:26, source: MailEnable
> 2020-08-26 03:45:49.9473|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: 183.82.152.35, user name: user@maildomain.com
> 08/26/20 03:45:31, source: MailEnable
> 2020-08-26 03:45:49.9673|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: 102.182.3.72, user name: user@maildomain.com
> 08/26/20 03:45:33, source: MailEnable
> 2020-08-26 03:45:49.9673|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: 122.173.191.7, user name: user@maildomain.com
> 08/26/20 03:45:38, source: MailEnable
> 2020-08-26 03:45:50.0398|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: 45.220.0.147, user name: user@maildomain.com
> 08/26/20 03:45:39, source: MailEnable
> 2020-08-26 03:45:50.0617|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: 103.136.156.2, user name: user@maildomain.com
> 08/26/20 03:45:41, source: MailEnable
> 2020-08-26 03:45:50.0850|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: 2.50.55.77, user name: user@maildomain.com
> 08/26/20 03:45:42, source: MailEnable
> ```

this is what i am talking about, i saw this in ipban itself.

**Comment by jjxtra** [comment]
These are all success logins, would you want them to be banned? If you want a failed login to ban immediately, you can set the config option for number of failed login attempts to 1, and be sure you have whitelisted your own ip addresses before doing this :)

**Comment by aloksharma1** [comment]
no these are from a hacked account thats why i want these banned.

**Comment by jjxtra** [comment]
I wouldn't feel comfortable adding something that bans successful logins, I would suggest changing account passwords and/or relying on the 1 failed login to ban option.

**Comment by aloksharma1** [comment]
ok, thanks for the input. i have already done that, i wanted to do this for old attempt. but i guess now the tool will take care of that if i just set it to 1 or 2.

**Comment by jjxtra** [comment]
Mail enable is now part of default config!
