### ISSUE TITLE
Blacklist specific or all IP's doesn't work

### ISSUE THREAD

**Issue by gnopscorp** [DigitalRuby/IPBan#106]
Operating System: Name: Windows, Version: 10.0.17763, Friendly Name: Microsoft Windows Server 2019 Standard
Version IPBan 1.5.5 > 1.5.7

Manually setting a block of specific IP's under ...

      <add key="Blacklist" value="46.12.x.x,212.56.x.x"/>

doesn't work. While I stopped the service and restarted IPBan again, the login to an RDP session still works from both of the IP's from above. Adding both IP's directly to the Windows Firewall to be blocked works perfectly fine. Also adding several Regex definitions to block these specific IP's or all IP's under

    <add key="BlacklistRegex" value=""/>

doesn't work. I tried many Regex-syntax proposals to ban all IP's or just the two IP's from above. No success. Whitelisting with the same Regex-syntax for these IP's works flawless.

**Comment by jjxtra** [comment]
You need to use the correct cidr mask for the blacklist. Anything in the blacklist will be added to a block rule in the firewall.

In your case it would be `46.12.0.0/16` and `212.56.0.0/16`.

http://www.subnet-calculator.com/cidr.php is a good website to figure out the correct cidr mask, but it's fairly straightforward. The / part is how many bits to mask out at the end. In the above examples, 16 bits (half of an ipv4 address) are masked out.

The blacklist regex should be a `.` if you want to blacklist everything after the first failed login.

**Comment by gnopscorp** [comment]
Not sure why you closed this. 

If I set the exact IP address it doesn't work. I just x'ed out my full IP's for privacy reasons. I'm fully aware of correct cidr-masks.
