### ISSUE TITLE
{year}, {month} and {day} placeholders

### ISSUE THREAD

**Issue by TheTitanrain** [DigitalRuby/IPBan#108]
How to use {year}, {month} and {day} placeholders for a log file?
If i provide the path like this <PathAndMask>C:\Program Files\...\security_log\VPN\sec_{year}{month}{day}.log</PathAndMask> IPBan try to read "sec_{year}{month}{day}.log" file.
`Adding log file to parse: C:\Program Files\...\security_log\VPN\sec_{year}{month}{day}.log`

**Comment by jjxtra** [comment]
The log sends out the original string, internally the log file scanner will replace those with the correct values.
