### ISSUE TITLE
2 regexp and 1 log file

### ISSUE THREAD

**Issue by TheTitanrain** [DigitalRuby/IPBan#114]
Hello!
Can i add multiple regexp to one log file?
I try to add two LogFile entry to config, but only first working.
![изображение](https://user-images.githubusercontent.com/1952721/94091502-b9265e80-fe5b-11ea-8802-c28c2805812c.png)

**Comment by jjxtra** [comment]
Definitely don't want multiple log file entries. Just use the | operator at the end of the first regex press enter and then start your second regex.

**Comment by TheTitanrain** [comment]
Thanks!
