### ISSUE TITLE
force unban behavior in this scenario where we are banning everything?

### ISSUE THREAD

**Issue by aloksharma1** [DigitalRuby/IPBan#115]
Hello,
i want to understand the force unabn.txt behavior where we have a server, which is under brute force for db passwords. we have put everything (success/failure ips) under ban. now anyone who wants to access db have to get it whitelisted before external access.
so in this case if i put unban.txt will it unban the user for whole day or will he be blocked in the next log parsing cycle? right now we manually add ip ranges under whitelist.

understating how unban works will help us automate things.

regards

**Comment by jjxtra** [comment]
Adding the `unban.txt` file simply removes bans only, it does not whitelist anything. So if you have a user that is blocked that you want to unblock but not whitelist, `unban.txt` file is the way to go.
