### ISSUE TITLE
 one click install doesn't work on 32-bit systems

### ISSUE THREAD

**Issue by 29039** [DigitalRuby/IPBan#116]
Thank you for your hard work Jeff. The latest version certainly makes things a lot easier to install, which I appreciate.

Just telling you know that the "one click install" command installs the 64-bit version on a 32-bit system.

I was able to overcome it by pasting the contents of the ZIP file for 32-bit into C:\Program Files\IPBan and the service seems to start OK.

But perhaps the script can be updated to install the right version to make things easier.

I appreciate that you are even building for 32-bit Windows. I have a hard to replace App that needs it so hoping that 32-bit Windows will stick around with security updates for a while.

**Comment by jjxtra** [comment]
You'll have to install the 32 bit manually or tweak the powershell script to point to the x86 build for Windows.

**Comment by 29039** [comment]
Thanks. Maybe the script could at least throw an error for 32-bit or the website warn? because took me a while to figure out why it wasn't working?

**Comment by jjxtra** [comment]
I will consider that, sure...

**Comment by 29039** [comment]
thanks!

**Comment by jjxtra** [comment]
I tweaked the powershell script a bit, let me know if it works at all on 32 bit Windows

**Comment by 29039** [comment]
Appreciate the fast response. I tested it on Windows 10 20H2 32-bit and it successfully installs the service.

Whether IPBan is actually working properly or not under 32-bit, that is testing for when I have more time

**Comment by 29039** [comment]
I just noticed that it is now installing to Program Files (x86) on the 32-bit system. The convention on 32-bit windows is to use just "Program Files", "Program Files (x86) is for 32-bit apps running on 64-bit windows.

**Comment by jjxtra** [comment]
Ooops sorry spaced that one, updated...
