### ISSUE TITLE
is it possible to check/query some ip/iplist in current ban list? 

### ISSUE THREAD

**Issue by aloksharma1** [DigitalRuby/IPBan#118]
hi, 
i would like to know if a supposed ip is banned by ipban system. Is their any way to query the db when someone is requesting to whitelist or any other connectivity issues. this will help to know by logs why particular ip was banned and if we should unban or not.

thanks

**Comment by jjxtra** [comment]
ipban.sqlite can be queried from any tool that can read sqlite. There is an ip address column, date of ban, number of failed logins and a source to indicate which system was attacked.
