### ISSUE TITLE
Issues with getting IPban to run on RDS VM 

### ISSUE THREAD

**Issue by SmartIT-AT** [DigitalRuby/IPBan#119]
Hi Jeff,

I currently get this issue when I have installed IPban 1.58 via zip on a RDS VM running Windows Server 2016, 
is this something that can be bypassed to get IPban working?

Please see the below error. 

|ERROR|DigitalRuby.IPBanCore.Logger|Error on IPBanService.RunCycleAsync: System.ApplicationException: Configuration failed to load, make sure to check for XML errors or unblock all the files.
   at DigitalRuby.IPBanCore.IPBanService.UpdateConfiguration()
   at DigitalRuby.IPBanCore.IPBanService.RunCycleAsync()

**Comment by jjxtra** [comment]
I don't see the error running from admin powershell:

```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/DigitalRuby/IPBan/master/IPBanCore/Windows/Scripts/install_latest.ps1'))
```

Is this what you ran?

**Comment by lansalot** [comment]
Before you unzipped it, did you unblock the file first in Explorer?
