### ISSUE TITLE
bad logging for multiple ban times

### ISSUE THREAD

**Issue by crystalgreen** [DigitalRuby/IPBan#123]
Hi, related to issue #121. I find the log message confusing:

> 2021-01-07 08:36:00.4731|WARN|DigitalRuby.IPBanCore.Logger|Banning ip address: 183.89.213.18, user name: administrator, config black listed: False, count: 6, extra info: , duration: 1.00:00:00
> ...
> 2021-01-08 08:36:15.0520|INFO|DigitalRuby.IPBanCore.Logger|**Ban duration 7.00:00:00 at index 1** expired for ip 183.89.213.18
> 2021-01-08 08:36:15.0523|WARN|DigitalRuby.IPBanCore.Logger|Preparing ip address 183.89.213.18 for next ban time 7.00:00:00

Using 

```xml
<add key="BanTime" value="01:00:00:00,07:00:00:00"/>
```

Here, the first time the IP was banned 1d ago and after that expiry one gets above log. I'd expect the log to state the expiry of the _current_ ban time (here 1d at index 0) and not the next one (7d). Is reporting the index a good idea? One would have to know if it is 0 or 1 based. Reporting only the time span should be enough to find the position.

Furthermore, the code only works if the ban times are in strictly ascending order which is probably the case more often than not but it's not guaranteed. Otherwise, the code will not respect the correct times but always take the first time in the list that is larger than the last current. Example: "2,1,3" -> start with 2, next time would be 3.

In order to know the current ban time index for sure may require storing the index which may be overkill and which could cause trouble if the config changes. IMO one should require the user to provide only strictly ascending times (no repeating times) and maybe the code should sort them to be sure (during config read) and write a log if the order changed during sort. Finally we report the previous time and index before `span < banTimes[i]`, i.e. the one at `i-1` if i > 0. 
The requirement (strictly ascending) is necessary to ensure the correct position _i-1=current time_ is logged. The _strict_ is required because two equal times will not work as the code will always find the last one and skip the others. Example: "1,2,2,3" will effectively use 1,2,3.

If you like I could make the changes and provide a pull request.

**Comment by jjxtra** [comment]
Feel free to submit a pr. You are correct they are expected to be in ascending order.

**Comment by jjxtra** [comment]
Closed via #126

**Comment by jjxtra** [comment]
PR is merged, thanks so much for the contribution!

**Comment by crystalgreen** [comment]
You're welcome. Thank you for sharing the software!
PS: This is the first .net 5 project I see out there. Impressive. I learned a lot about the build setup.
