### ISSUE TITLE
Any plans to implement minimize to tray ?

### ISSUE THREAD

**Issue by olluz** [DigitalRuby/IPBan#127]
Thanks

**Comment by jjxtra** [comment]
Probably not, this runs as a windows or linux service with no gui

**Comment by olluz** [comment]
thanks for the prompt reply. Sorry, then for the silly question:
If I execute DigitalRuby.IPBan.exe this will start the service and I can just close the window...the service will still run in the background ?
Thanks again

**Comment by jjxtra** [comment]
You can run from a console and do that if you want to see the output interactively, but most people will use the install script to set it up as a service. Either way there are no plans to minimize to tray.

**Comment by olluz** [comment]
Ok, now I got it. Thanks again
