### ISSUE TITLE
Expand-Archive not available on Windows 2012 R2

### ISSUE THREAD

**Issue by funforums** [DigitalRuby/IPBan#128]
Hi,
I'd like to let you know that running the Powershell install command on a Win2012 R2 machine, a missing Cmdlet was used: Expand-Archive. It seems it belongs to Powershell 5.1, where Win2012 R2 does not come with that PS version by default (seems here it runs with 4.0).

Ref:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-5.1

Cheers, and thanks for the great work you put in this project.

EDIT: I have now inspected the script and seen that it indeed reports PS 5.1 as requirement and provides a link to update it on older servers. It would be perfect if you could also update the front README instructions for Windows!

**Comment by jjxtra** [comment]
I've updated the script to report an error to console if ps version is not high enough
