### ISSUE TITLE
Process to run on unban

### ISSUE THREAD

**Issue by Nialsihg** [DigitalRuby/IPBan#131]
Hi,

I'm using the new ProcessToRunOnUnban option and I was expecting it to get called upon restart when ClearBannedIPAddressesOnRestart is true for each unbanned IP but that doesn't seem to be the case.

Is it something that we might see in a future update?

Thanks for the great work!

**Comment by jjxtra** [comment]
Sure yea makes sense

**Comment by jjxtra** [comment]
Fixed by 21afcc672aa4bdd0eed21d8a4ae43038ddeca027

**Comment by Nialsihg** [comment]
Thanks for the quick fix!

Could you make a new release so I can update easily?

**Comment by jjxtra** [comment]
Yep! Had appendix out a few days ago so I'm a little slow, but I'll get one made today.

**Comment by jjxtra** [comment]
1.6.0 is out

**Comment by Nialsihg** [comment]
Thank you very much and rest well :)

**Comment by jjxtra** [comment]
You are very welcome
