### ISSUE TITLE
Uninstall script references incorrect installation directory

### ISSUE THREAD

**Issue by eponerine** [DigitalRuby/IPBan#132]
The installation installs files to `C:\Program Files\IPBan`, so trying to remove the following directory will fail.

https://github.com/DigitalRuby/IPBan/blob/666ac4281a6b7747cc010fa936299c97902b353e/IPBanCore/Windows/Scripts/uninstall.cmd#L3

**Comment by jjxtra** [comment]
Fixed by 525c52da6cc36c87482356016cf89836540ab5bd

**Comment by eponerine** [comment]
How.... is that fixing the issue of the script _NOT_ deleting the directory the files are installed in? Am I missing something?

**Comment by jjxtra** [comment]
Sorry had my appendix out and coming off meds. There are two install scripts using two folders. Will add the 2nd one now.
