### ISSUE TITLE
Version info

### ISSUE THREAD

**Issue by RvdHout** [DigitalRuby/IPBan#133]
Not a big issue, but latest release version numbering is still tagged as being 1.5.9 apposed to 1.6.0

**Comment by RvdHout** [comment]
Ps, might be a idea to include IPBan version information tot log when the server first start, for example:

> 2021-02-13 13:41:26.1138|WARN|DigitalRuby.IPBanCore.Logger|Initializing service
> 2021-02-13 13:41:26.1797|WARN|DigitalRuby.IPBanCore.Logger|Detecting os version...
> 2021-02-13 13:41:26.2836|WARN|DigitalRuby.IPBanCore.Logger|OS version detected: Name: Windows, Version: 10.0.19041, Friendly Name: Microsoft Windows 10 Pro, Description: Microsoft Windows 10.0.19041
> 2021-02-13 13:41:26.3255|WARN|DigitalRuby.IPBanCore.Logger|Running as a Windows service
> 2021-02-13 13:41:26.4437|WARN|DigitalRuby.IPBanCore.Logger|Preparing to run service
> 2021-02-13 13:41:26.4676|WARN|DigitalRuby.IPBanCore.Logger|Starting service
> 2021-02-13 13:41:26.4676|WARN|DigitalRuby.IPBanCore.Logger|Running service
> 2021-02-13 13:41:26.9655|WARN|DigitalRuby.IPBanCore.Logger|IPBan _**1.6.0**_ is free software created and refined over many years.

**Comment by RvdHout** [comment]
> Not a big issue, but latest release version numbering is still tagged as being 1.5.9 apposed to 1.6.0

the assembly/executable i mean with above remark

**Comment by jjxtra** [comment]
Re-posting 1.6.0 with correct version and version in the log
