### ISSUE TITLE
Parameter to specify the log level of individual Log rules

### ISSUE THREAD

**Issue by dfun90** [DigitalRuby/IPBan#135]
Hi there!

My co-worker and I were wondering if there is a possibility to get a feature added to specify the log level for each `FailedLoginRegex` and `SuccessfulLoginRegex` within an individual `<LogFile>` block.  

This would allow to have much cleaner log files, since you can then specify in the `nlog.config` in what file to log e.g. `INFO` or `WARN` messages. Right now I saw that the log level of a failed and successful login is hardcoded to `WARN` in the code.

This is how an example config entry could look like:
```xml
<LogFile>
        <Source>Dummy</Source>
        <PathAndMask>C:\Program Files (x86)\Test\Logging\*.log</PathAndMask>
        <Recursive>false</Recursive>
        <FailedLoginRegex><![CDATA[      ]]></FailedLoginRegex>
         <FailedLoginLogLevel>WARN</FailedLoginLogLevel>
        <SuccessfulLoginRegex><![CDATA[     ]]></SuccessfulLoginRegex>
         <SuccessfulLoginLogLevel>INFO</SuccessfulLoginLogLevel>
        <PlatformRegex>Windows</PlatformRegex>
        <PingInterval>10000</PingInterval>
        <MaxFileSize>16777216</MaxFileSize>
</LogFile>
```

Thanks and keep up the good work!

**Comment by jjxtra** [comment]
Moved to https://github.com/DigitalRuby/IPBan/discussions/138

**Comment by jjxtra** [comment]
Resolved in https://github.com/DigitalRuby/IPBan/discussions/138
