### ISSUE TITLE
is there a switch to disable rules,or just remove blocks from ipban.config?

### ISSUE THREAD

**Issue by ivantao8** [DigitalRuby/IPBan#144]
hi,
seems ipban trying to scan apps whitch not installed, like:
`2021-04-25 09:25:54.0057|INFO|DigitalRuby.IPBanCore.Logger|Adding log file to parse: C:/SmarterMail/logs/**/*.log`
whats the proper way to turn a rule off?
thanks.

**Comment by jjxtra** [comment]
You can remove the entry from the config. There are a number of default log files that are parsed. If the files do not exist, it will not add any overhead.
