### ISSUE TITLE
Question about IPBAN - Is there something that I have not set correctly?

### ISSUE THREAD

**Issue by Mahungchi** [DigitalRuby/IPBan#149]
Hi Jeff,

I've observed from the logfile.txt of IPBAN that it has successfully blocked many IPs.
![ipbanlog](https://user-images.githubusercontent.com/7196326/117910583-ca4ead80-b30e-11eb-8b0a-582070ee5cb6.png)

However, I tried to access this host with IPBAN by entering the wrong password 5 times in a row, I can still access it without being blocked by IPBAN.

I would like to ask you if there is something that I have not set correctly. Thank you!

**Comment by jjxtra** [comment]
Is your ip in windows firewall in the ipban block rule?
