### ISSUE TITLE
Whitelist with DDNS entry

### ISSUE THREAD

**Issue by CrazyHenk44** [DigitalRuby/IPBan#157]
Hello,

Thanks for the lovely software. I have one customer that has a changing ip-address. I've seen that you added Dynamic DNS support a while back, but I don't seem to understand how it works. 

I added the Dynamic DNS entry in the whitelist, lets's say 'customer.ddns.provider.com'. When i restart IPBan, I can see in the Windows Firewall whitelist section the IP-address that is currently associated with that DNS name. 

Then the customer gets a new IP address, 'customer.ddns.provider.com' changes to that IP-address correctly. I've now waited 24 hours, but the Windows Firewall whitelist section still shows the old IP-address. 

Can you explain a bit how this should work?

**Comment by CrazyHenk44** [comment]
ping?

**Comment by jjxtra** [comment]
Every cycle it will check if it's time to re-evaluate the ip addresses for each dns entry. If time expires it does a dns query and updates the firewall. Whitelist is a little different. It simply prevents blocking. There is no dedicated firewall rule unless a hard coded ip is entered in the whitelist property.

**Comment by CrazyHenk44** [comment]
> Every cycle it will check if it's time to re-evaluate the ip addresses for each dns entry. If time expires it does a dns query and updates the firewall. 

Which setting are you talking about if this is not about the whitelist?

>Whitelist is a little different. It simply prevents blocking. There is no dedicated firewall rule unless a hard coded ip is entered in the whitelist property.

I did add the ddns entry to the whitelist and it is never updated after the initial start.

Thanks for taking the time to help.

**Comment by jjxtra** [comment]
Just did some debugging. After 5 minutes the configuration will force reload which does re-populate the dns entries even if the config file has not changed.

**Comment by CrazyHenk44** [comment]
so, just to clarify. You added 'a.b.com' to the whitelist. It points to 1.2.3.4 for example. Then you start IPBan, it adds 1.2.3.4 to the windows firewall whitelist. 

Then you change the a.b.com to point to 5.6.7.8. Without doing anything after 5 minutes the windows firewall shows 5.6.7.8 in the whitelist list?

**Comment by jjxtra** [comment]
That's the behavior I am seeing. I had to set the ttl low on my dns and run `ipconfig /flushdns`

**Comment by CrazyHenk44** [comment]
Can you reopen this issue please?

**Comment by jjxtra** [comment]
Performed a test with latest version using a dns record on my domain of 1.1.1.1. Saw this appear in firewall. Then 30 seconds later I changed same dns to 1.1.1.2. 5 minutes later upon config refresh interval being hit, I saw firewall whitelist update to 1.1.1.2.
