### ISSUE TITLE
log says config updated, but changes don't take effect

### ISSUE THREAD

**Issue by rmeden** [DigitalRuby/IPBan#162]
Windows Server 2012R2
IPBAN 1.6.0

If you edit the ipan.config file, you get a message in the running log that the config file changed.  Great!  Only problem is that lead me to assume that the new config was loaded!  I just spent hours trying to tweak a FailedLoginRegex and couldn't figure out why it wasn't working... turns out the new regex wasn't loaded w/o restarting the program!

I suggest you reload regex or not display that the log changed.

**Comment by jjxtra** [comment]
Looks like only the path and mask will trigger a reload of the log file, I will create a 1.6.1 patch that compares all options every cycle to detect the change.

**Comment by jjxtra** [comment]
Fixed by e431ec6dd341de205f4d818c0d8d5d4213434586
