### ISSUE TITLE
Log not updating?

### ISSUE THREAD

**Issue by kimboslice99** [DigitalRuby/IPBan#174]
In the past I noticed the log would update every 15 seconds (as specified by the config)

Suddenly now the log only updates when an IP has been banned? 

Did I break something? I've completely deleted and reinstalled ipban, but it looks like my entire config came back? 

thoroughly confused.... where else is the config stored so that I can "reset" ipban?

**Comment by jjxtra** [comment]
Can you give more details here? What is the expected behavior exactly and what behavior are you seeing? You can always sc.delete ipban and then remove the folder and re-install.

**Comment by TurboFiero** [comment]
Well, I'm not sure what the expected behaviour really should be, just that I previously saw it updating at 15 second intervals. But now 5-10 minutes goes by with no update? I had poked around in the config, figured I broke something....

But after running `sc.exe delete ipban`, deleting the IPBan folder, and reinstalling via powershell admin prompt I have the original config, and still the same behaviour, so I'm not sure now, which is why I figured it couldn't hurt to ask

**Comment by jjxtra** [comment]
What were you seeing in the log before every 15 seconds? I did adjust some log levels so there was a reduction in verbosity.

**Comment by TurboFiero** [comment]
just a list of IPs that were banned (or pending?) IIRC, perhaps it is the log level?

Can I set log level here? `<logger name="*" minlevel="Info" writeTo="logfile"/>`

**Comment by jjxtra** [comment]
Yea try setting the `minLevel` to `Debug`

**Comment by kimboslice99** [comment]
That gives a lot more info, but I must not have had it set to debug, since its a ton more than I had once saw (which i certainly appreciate when needed)

Perhaps the behaviour I saw before was out of the ordinary, and what im seeing now is normal?

 I suppose I'll close this since it may not really be an issue, but I would still appreciate any input as to why I might be seeing such a drastic change in logging

**Comment by jjxtra** [comment]
I changed a bunch of log levels in a recent update from Info to Debug.

**Comment by kimboslice99** [comment]
Alrighty, that must be it. I'll only bug you with one more question, if I want to set the log location can i just change 

`"${basedir}/logfile.txt"`

to `"C:\path\to\logfile.txt"`?

**Comment by jjxtra** [comment]
Yup! You might user forward slashes...

**Comment by kimboslice99** [comment]
Awesome, used forward slashes, thanks m8, Appreciate the help
