### ISSUE TITLE
AbuseIPDB Integration

### ISSUE THREAD

**Issue by kimboslice99** [DigitalRuby/IPBan#179]
Perhaps I'm doing something wrong, not entirely sure...

Followed the example config found under Recipes/Windows/Integrations, but its not sending any reports? I was able to fetch the blacklist just fine with the task scheduler 

Powershell 7 is installed and is found under C:\Program Files\PowerShell\7\pwsh.exe, and I inserted my API key to the example config

I placed the piece of the example config _between_ `<appSettings>` and `</appSettings>` into my config right underneath `<appSettings>` 

Should I be giving it it's own <appSettings> block entirely? Or has something changed with their API? My other "ProcessToRunOnBan" completes fine, but not the provided config, unsure how to proceed, please advise

**Comment by jjxtra** [comment]
Hard to say without seeing your exact config item. Feel free to mask out the api key.

**Comment by kimboslice99** [comment]
```
  <appSettings>
  
   <!-- read blacklist from temp file every hour -->
   <add key="FirewallUriRules" value="
AbuseIPDB,00:01:00:00,file://c:/windows/temp/abuseipdb_blacklist.txt
   "/>
  
   <!-- report banned IPs back to AbuseIPDB -->
   <add key="ProcessToRunOnBan" value="C:\Program Files\PowerShell\7\pwsh.exe|-Command &quot;Invoke-WebRequest -Uri 'https://api.abuseipdb.com/api/v2/report?ip=###IPADDRESS###&amp;categories=18' -Method 'POST' -Headers @{'Accept'='application/json';'Key'='000000000000000000000MYAPIKEY00000000000000000000000000000000000000000'}&quot;"/>
  
    <!-- Number of failed logins before banning the ip address -->
    <add key="FailedLoginAttemptsBeforeBan" value="5"/>
```

This is where it is in the config, I'm terrible with powershell.... I guess I shouldn't be following the config example so closely?

**Comment by kimboslice99** [comment]
Ok so I moved the config further down near the other "ProcessToRunOnBan" and restarted, its now sending reports, but its not running the second "ProcessToRunOnBan" which previously worked fine... can there be only one?

**Comment by jjxtra** [comment]
Like Highlander, there can be only one. You can put a script in there with arguments and then call multiple scripts in that script.

**Comment by kimboslice99** [comment]
Was the first thing that came to mind! heh

If I was calling a batch file before, how would I go about calling both? I was using powershell Get-Content with -replace to put the IP into a vbs that sent an email

Also, is the right way to do the "FirewallUriRules" like so?


 ```
   <add key="FirewallUriRules" value="
         EmergingThreats,01:00:00:00,https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt
		 AbuseIPDB,00:01:00:00,file://c:/windows/temp/abuseipdb_blacklist.txt
    "/>
```

**Comment by jjxtra** [comment]
https://www.red-gate.com/simple-talk/sysadmin/powershell/how-to-use-parameters-in-powershell/

Firewall rules is correct, newline delimited

**Comment by kimboslice99** [comment]
I don't really understand how to make "Invoke-webrequest" work to begin with

Thanks anyhow!

**Comment by kimboslice99** [comment]
Just a thought, would be nice to be able to call more than one process upon ban, makes it awfully difficult for an average user to come up with a wacky script to work around this

Either way thanks for all the work you do! Greatly appreciated

**Comment by jjxtra** [comment]
I'm sending a refresh of 1.7.1 release that will allow newline delimited processes similar to the firewall uri rule. Try download in about an hour.

**Comment by kimboslice99** [comment]
Working perfectly! Thank you! Words cannot express how much I appreciate this!

**Comment by jjxtra** [comment]
You're welcome, enjoy!

**Comment by kimboslice99** [comment]
Oi m8, I noticed something in the AbuseIPDB Reporting Policy 

`Report MUST contain a detailed description of the attack. Recommended details to include are: port number, payload, and timestamp.
`

How might one add these required details?

**Comment by kimboslice99** [comment]
After some testing I have figured out this much, I suppose it'd be acceptable to simple put 'Brute force' according to their report policy, it just has to have any comment, but if i wanted a timestamp or something, how could I do that? Something like ###TIME###?

 `C:\Program Files\PowerShell\7\pwsh.exe|-Command &quot;Invoke-WebRequest -Uri 'https://api.abuseipdb.com/api/v2/report?ip=###IPADDRESS###&amp;comment=testing&amp;categories=18' -Method 'POST' -Headers @{'Accept'='application/json';'Key'='MYAPIKEY'}&quot;
`

**Comment by jjxtra** [comment]
Power shell should have a way to get the time stamp

**Comment by kimboslice99** [comment]
Ok I suppose I need to dig into Powershell more

I read through the 'wiki' and I cant find an explanation of what the values like "###VERSION###" are supposed to be filled with, in my testing I cant get these to actually be filled, the output of "###MACHINENAME###" just stays as is? Does the windows version not use these?

**Comment by kimboslice99** [comment]
Not to muddy up the thread, but...

I have a config for Emby you may want to add to the recipes, works perfectly as of version 4.6.7.0
  ``` 
      <LogFile>

        <Source>Emby</Source>
        <PathAndMask>C:/Users/USER/AppData/Roaming/Emby-Server/programdata/logs/embyserver.txt</PathAndMask>
		<Recursive>true</Recursive>
        <FailedLoginRegex>
          <![CDATA[
              Warn\sServer:\sAUTH-ERROR:\s(?<ipaddress>.+?)?\s-\sInvalid*
          ]]>
        </FailedLoginRegex>
        <PlatformRegex>Windows</PlatformRegex>
        <PingInterval>10000</PingInterval>
        <MaxFileSize>16777216</MaxFileSize>
        <FailedLoginThreshold>5</FailedLoginThreshold>

      </LogFile>

 ```

**Comment by kimboslice99** [comment]
Thanks for that link you posted earlier! Here's a working script to add the timestamp to the comment

```
$date = (Get-Date)
$ipaddress=$args[0]

Invoke-WebRequest -Uri "https://api.abuseipdb.com/api/v2/report?ip=$ipaddress&comment=Brute Force on $date&categories=18" -Method 'POST' -Headers @{'Accept'='application/json';'Key'='MYAPIKEY'}
```

**Comment by kimboslice99** [comment]
There's definitely better ways of doing this, but here's a way of adding the related logs to the comment aswell, while striping any information you wouldnt want posted to AbuseIPDB (removes username, and the "DigitalRuby.IPBanCore.Logger" part of the log)

This took longer than I'd like to admit, but a great learning experience I suppose
```
$ipaddress=$args[0]
$logdir="C:\Program Files\IPBan\IPBan.txt"
$raw=Select-String -Path $logdir -Pattern "Login failure" -SimpleMatch | Where-Object {$_ -match "$ipaddress"} | Foreach {$_.Line} 
$log=$raw -replace "\|.+?\|.+?\|", " " -replace "[\,]*\,(.*?)\,", "" | Select-Object -Last 5

Invoke-WebRequest -Uri "https://api.abuseipdb.com/api/v2/report?ip=$ipaddress&comment=$log&categories=18" -Method 'POST' -Headers @{'Accept'='application/json';'Key'='APIKEY'}
```

Open to suggestions on how to improve?

**Comment by mycanaletto** [comment]
> I have a config for Emby you may want to add to the recipes, works perfectly as of version 4.6.7.0

Hi @kimboslice99 

I'm in the process of configuring it.

Do you have an idea for a regex to log successful connections, but also unsuccessful ones in order to extract the username?

merci ;-)

**Comment by kimboslice99** [comment]
The emby logs do not show the username that was attempted, so there is no way to know

**Comment by mycanaletto** [comment]
> The emby logs do not show the username

Thanks for this information.

**Comment by kimboslice99** [comment]
Sorry, I just checked, not sure when it got added or if its always been there (running the latest beta), but heres a failedloginregex you can use to get the username 

```
(Authentication\srequest\sfor\s(?<username>\S+)\shas\sbeen\sdenied\.\n)?(?<timestamp>[^\s]+\s[^\s]+)\sWarn\sServer:\sAUTH-ERROR:\s(?<ipaddress>[^\s]+)\s-\s(?<log>[^\n]+)
```

**Comment by mycanaletto** [comment]
It blocks well but it doesn't retrieve the username.

But what I was also trying to do is log valid connections.

![image](https://github.com/DigitalRuby/IPBan/assets/45459269/1cd0acc6-7093-4d8d-b2d6-fc18adadabc3)
