### ISSUE TITLE
Blocking issue

### ISSUE THREAD

**Issue by killmasta93** [DigitalRuby/IPBan#180]
Hi
I was wondering if someone could shed some light,
Currently trying to install on windows server 2022
`
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/DigitalRuby/IPBan/master/IPBanCore/Windows/Scripts/install_latest.ps1'))`

i disabled NTLM logins and also made sure the audit policy was working
```

auditpol /set /category:"Logon/Logoff" /success:enable /failure:enable
auditpol /set /category:"Account Logon" /success:enable /failure:enable
```

i ran a test to block myself but the logs on the ipban config does not show any movement

any ideas?

thank you

**Comment by jjxtra** [comment]
You don't have to disable ntlm unless you are on server 2012.

Did you see the login failure recognized in logfile.txt?

**Comment by killmasta93** [comment]
thanks for the reply, it seems that it was blocking just took a few mins, 
what i noticed i put the password wrong 10 times then it blocks which is odd because i have it to 5 
is the service immediately  or does it take time to look for the logs?
