### ISSUE TITLE
IPBan not removing unbanned IPv6 Addresses

### ISSUE THREAD

**Issue by kimboslice99** [DigitalRuby/IPBan#190]
It would seem IPBan is not removing unbanned IPv6 Addresses from the block rule in the firewall

Queuing an IPv6 address via ban.txt then unbanning via unban.txt, the IPv6 address is still in the firewall?

Happening on two separate servers... both on Server 2019/17763

**Comment by jjxtra** [comment]
I'll make a unit test for this, thanks for reporting!

**Comment by jjxtra** [comment]
Fixed in 75493b4756f301470346b5aad13ccc27e46d5142

**Comment by jjxtra** [comment]
https://github.com/DigitalRuby/IPBan/releases/tag/1.7.2

**Comment by kimboslice99** [comment]
Awesome! Thanks! Working perfectly

I have a couple of Powershell scripts for integration with Cloudflare that I'd like to share, I suppose I'll make a new thread to keep things organized?

**Comment by jjxtra** [comment]
Please add a pr for recipes folder? I believe this might be a good folder? https://github.com/DigitalRuby/IPBan/tree/master/Recipes/Universal

**Comment by jjxtra** [comment]
Or this: https://github.com/DigitalRuby/IPBan/tree/master/Recipes/Windows/Integrations
