### ISSUE TITLE
IPban Oddity

### ISSUE THREAD

**Issue by deejayducky** [DigitalRuby/IPBan#197]
I'm running this on my Win2019 Webserver and noticed one day that my websites stopped working (bear with me on this); and I was doing EVERYTHING to try to sort this out for obvious reasons... Ultimately after pulling my hair out for a day, I found out if I turn off my Firewall, it just worked... 

Okay... I go though all my rules in there and everything was normal, nothing out of the ordinary... so turned it back on, and websites stop working again. I do a "Reset firewall rules to defaults" and load one by one back in, and all seemed well. I then got IPban back in, and decided might as well upgrade to the latest version. (This problem is not version specific as it happened to the version I had before)

Low and behold, when I have IPban in "Allowed Apps" enabled, websites stop working, when I disable it, they start working again, and do not know why, as this worked before. (Im assuming when its disabled in allowed apps, that its not actually blocking anything, as I tried RDCing from a remote source just with wrong passwords, and while I see it show up in a rule to block in Windows FW, Im still able to connect.) Obviously if I enable the IPban entry in allowed apps, I get disconnected from my web based remote software running on said webserver, so I cant check to see if my ban goes through when its enabled.

<big breath>

What simple thing did I miss, it was working fine for years! Do I need to add my ISP's public IP in the whitelist? (whatever comes up from "What is my IP"?

**Comment by jjxtra** [comment]
Hi there. Are you using the free IPBan? When you start IPBan what rules get created in Windows firewall? Is your server's ip address one of them?

**Comment by jjxtra** [comment]
If you can send your ipban.sqlite file to me that would be helpful, along with your server ip. Send it to support@ipban.com

**Comment by deejayducky** [comment]
Thanks will do, in my normal fashion Im mucking things up a bit, so since I couldn't figure out easily how to uninstall (I know the reference just says use the uninstall flag on the install script) its not overly documented for a older guy like me. so I just stopped the service, deleted all the entries for IPban, and restarted the service and that recreated the entries.

Trying things out.

Can you show me the location of the command to uninstall just so I have it in the future, and also in the case of a webserver, would I whitelist the public facing IP? 

I'll get you the file when I finish my up to date testing.

**Comment by jjxtra** [comment]
Easiest is to:
```
sc stop ipban
sc delete ipban
# then delete the c:/program files/ipban folder
```

**Comment by jjxtra** [comment]
Script is here: https://github.com/DigitalRuby/IPBan/blob/master/IPBanCore/Windows/Scripts/uninstall.cmd

**Comment by deejayducky** [comment]
Thanks! I think its working again... dunno what I did but clearly it worked! (Sometimes its just best to start over from scratch) I'll reopen this thread if I run into any issues... still not sure what IPban blocked that killed the webservers I host.

**Comment by jjxtra** [comment]
If it does happen again, send me the file and also try to find the blocked ip in the event viewer and send me the xml. Hopefully we can find the trigger that misfired.
