### ISSUE TITLE
Win2019 Std x64 Service IPBAN 

### ISSUE THREAD

**Issue by LogSpider** [DigitalRuby/IPBan#201]
Everything works fine when i start IPBan manually. Firewall Rules are added in cause of regex config. IPs are blocked. Nice. When i start IPBAN service, it throws `ip ban is not a valid win32 application` windows err-id 7000. err 193.

How can i solve this?

**Comment by jjxtra** [comment]
How did you install?

**Comment by LogSpider** [comment]
I don't know why but there was a File c:\Program* that caused this error. Solved.
