### ISSUE TITLE
Disappearing IPBan_GlobalBlacklist_0 and IPBan_WhiteBlacklist_0

### ISSUE THREAD

**Issue by onegrasshopper** [DigitalRuby/IPBan#202]
There seems to be a bug with the timing of refreshing Blacklist and Whitelist? Is this affected by some config?

Watching Windows Firewall (either keep polling on a powershell line, or flipping back and forth Monitoring/Inbound in the GUI):

IPBan_GlobalBlacklist_0 and IPBan_GlobalWhitelist_0 rules will disappear periodically. And take a long while (minutes) to reappear. When these disappear, the rules are really gone for that duration. A quick test shows Blacklist IPs are allowed to connect.

**Comment by jjxtra** [comment]
The global blacklist and global whitelist will be updated everytime the configuration changes, or when the config is force reloaded (about every 5 minutes).

**Comment by onegrasshopper** [comment]
Yes, Windows Firewall as referenced. Win10 Pro 20H2, current IPBan version.

Nothing external deleting those two rules. The other IPBan_Block_0 and EmergingThreats_0 / EmergingThreats_1000 rules do not exhibit this deleted-for-a-while/recreated behavior. Normal banning/unbanning is working fine.

Only the IPBan_GlobalBlacklist_0 and IPBan_GlobalWhitelist_0 stay deleted for a period.

No errors in logfile.txt to correlate but "Config file changed" is logged often despite having no change. 

I will strip down my ipban.override.config and reproduce with minimal entries. Right now I have a few CIDR addresses in Whiltelist and Blacklist. And when the IPBan_GlobalBlacklist/Whiltelist rules exist, they are there correctly.

**Comment by jjxtra** [comment]
I wonder if it's the override file? Does the error happen if you remove the override file and put it all in the ipban.config file?

**Comment by jjxtra** [comment]
If you can send your ipban.config and ipban.override.config to my email - support@ipban.com I can check if anything looks like it could be a problem.

**Comment by onegrasshopper** [comment]
Okay, I've tried to reproduce this. Not reliably. But it has to do with changes to ipban.config (or .override)

I noticed this after restarting the service, removed the override file, deleted everything in the ipban.config except for appsettings and the one ipban generic logfile node. Worked fine.

Dropped in a few ip addresses into a ban.txt to have some entries.  Picked up fine.

Then, I kept saving/editing a ipban.override.config file (nothing except Blacklist or Whitelist appsettings and editing their strings), to which IPban picks up the changes.  

But at some point logfile.txt starts showing "Config file changed" lines, sometimes twice in a span of minutes when changes are no longer made.  

It is at this time/state that the IPBan_GlobalBlacklist/Whitelist starts getting deleted after a short time and then recreated after a long delay.

A restart of IPBan service corrects the behavior. So there's probably some timing condition in the config/override file change updating tasks?

Also did the following.  Default install IPBan. Add ipban.override.config like below and just kept adding to Blacklist value in an editor, saving as I went along. The behavior occurred.

<configuration>
  <appSettings>
	<add key="Whitelist" value="10.0.0.222"
	/>
	<add key="Blacklist" value="162.142.125.0/24,10.0.0.123"
	/>
  </appSettings>
</configuration>


Hope that helps.

**Comment by jjxtra** [comment]
Please try release https://github.com/DigitalRuby/IPBan/releases/tag/1.7.3 and let me know if it's any better.

I identified a bug where if the base config did not have an appSettings/key that the override config did have, it would not merge.

**Comment by onegrasshopper** [comment]
Unfortunately not. I can reproduce similarly in the steps above.

Once I keep editing/saving the [override.]config files, either Whitelist, Blacklist values or a comment, at some point, the log starts doing this repeatedly

2022-06-16 15:58:41.0830|INFO|IPBan|Config file changed
2022-06-16 16:02:41.8474|INFO|IPBan|Config file changed
2022-06-16 16:02:41.8793|INFO|IPBan|Adding log file to parse: T:/tmp/logs/IPBanCustomLogs/*.log
2022-06-16 16:03:42.2334|INFO|IPBan|Config file changed
2022-06-16 16:07:43.1151|INFO|IPBan|Config file changed

and IPBan_GlobalBlacklist/Whitelist is deleted / recreated briefly after some time

**Comment by jjxtra** [comment]
Did you set your nlog.config to Debug level?

**Comment by onegrasshopper** [comment]
yes, though I didn't attach and that would have been pertinent, sorry.

Below is what it looks like once the issue starts happening. Looks like the two Config file changed lines causes a state change between having ip addresses and 0 ip addresses!

2022-06-17 09:37:44.5425|DEBUG|IPBan|Updating global whitelist with 5 ip addresses
2022-06-17 09:37:45.2695|DEBUG|IPBan|Updating global blacklist with 56 ip addresses
2022-06-17 09:39:46.3938|INFO|IPBan|Config file changed
2022-06-17 09:39:46.4198|DEBUG|IPBan|Updating global whitelist with 0 ip addresses
2022-06-17 09:39:46.5190|DEBUG|IPBan|Updating global blacklist with 0 ip addresses
2022-06-17 09:42:47.0183|INFO|IPBan|Config file changed
2022-06-17 09:42:47.0730|INFO|IPBan|Adding log file to parse: T:/tmp/logs/IPBanCustomLogs/*.log
2022-06-17 09:42:47.0730|DEBUG|IPBan|Updating global whitelist with 5 ip addresses
2022-06-17 09:42:47.1958|DEBUG|IPBan|Updating global blacklist with 56 ip addresses
2022-06-17 09:44:47.4615|INFO|IPBan|Config file changed
2022-06-17 09:44:47.4792|DEBUG|IPBan|Updating global whitelist with 0 ip addresses
2022-06-17 09:44:47.5727|DEBUG|IPBan|Updating global blacklist with 0 ip addresses

**Comment by jjxtra** [comment]
Can you email me your ipban.override.config file to support@ipban.com? That will help me start trying to reproduce this exactly as you are doing it...

**Comment by onegrasshopper** [comment]
Nothing special in the test ipban.override.config, so I included it here in case others wanted to test (hope that's okay instead of email). Hope this helps!

Exact steps to repro:
* Open in notepad (ipban running, default ipban.config). 
* Constantly manually edit and save in notepad. I did it with adding one whitelist, change the comment, add another blacklist, etc. 


<?xml version="1.0"?>
<configuration>
  <appSettings>
	<add key="UseDefaultBannedIPAddressHandler" value="false" /> 
	<add key="FailedLoginAttemptsBeforeBan" value="2"/>
	<add key="BanTime" value="03:00:00:00"/>
	<add key="ExpireTime" value="10:00:00:00"/>
	<add key="CycleTime" value="00:00:00:30"/>
	<add key="Whitelist" value="127.0.0.1,127.0.0.2"
	/>
	
	
	
	<add key="Blacklist" value="52.95.229.0/24,54.72.0.0/15"
	/>

  </appSettings>
</configuration>

**Comment by jjxtra** [comment]
I've reproduced this after about 15 minutes of trying so I will get a breakpoint in and try to see what the trigger is.

**Comment by jjxtra** [comment]
Doing the script helped reproduce it within a few minutes. I am seeing a ipban.config change notification from the 5 minute interval that then has a null override xml config. I am still tracking down why the override config comes back null in these cases.

**Comment by jjxtra** [comment]
I believe I have tracked down the problem, C# File.Exists call can sometimes return false if an IO operation is in progress on the file. So I am adding a fallback to actually try to open the file and see if it throws a file not found exception or some other error. If it is some other error it will retry a few times to see if it can determine the file really exists, and if not it will throw an exception.

**Comment by jjxtra** [comment]
@onegrasshopper Please try the 1.7.3 build again, I refreshed it with a more robust file check

**Comment by onegrasshopper** [comment]
Seems to be good so far with the refreshed 1.7.3.  Has been okay with random edits over the past two days.

**Comment by jjxtra** [comment]
Thanks. Please re-open if you see any further issue.
