### ISSUE TITLE
Feature request? Parsing as IP Failed - log what service this comes from

### ISSUE THREAD

**Issue by kimboslice99** [DigitalRuby/IPBan#204]
I'm seeing a _lot_ of this in logs
```
2022-06-30 13:27:14.1143|INFO|IPBan|Parsing as IP failed, checking dns 'localhost'
2022-06-30 13:27:14.1143|INFO|IPBan|Dns result 'localhost' = '::1'
```
But I have no way of knowing what is doing this, without pouring over a dozen+ logs... It would be nice to see what service is doing this, without having to go through all the logs

**Comment by kimboslice99** [comment]
Awesome! Much appreciated, thanks!

But if localhost is ignored, then will I still see what service is doing this?

**Comment by jjxtra** [comment]
No I suppose not, I can do a build without it first.

**Comment by kimboslice99** [comment]
Perhaps if it were a configurable option that would be ideal? maybe tie it to the "ProcessInternalIPAddresses" key

**Comment by jjxtra** [comment]
Please try refresh of 1.7.3 release

**Comment by kimboslice99** [comment]
I've noticed a bug, whitelisted IPv6 addresses arent recognized as whitelisted and IPBan tries to ban the address anyways

Should I open a new thread for this?

**Comment by jjxtra** [comment]
Sure, although I believe I fixed something with windows firewall for ipv6, but I will run some tests to be sure

**Comment by jjxtra** [comment]
A quick test confirms that ipv6 whitelisting is working, can you share the ipv6 that is failing and your ipban.config file to support@ipban.com?
