### ISSUE TITLE
Block all, except whitelisted

### ISSUE THREAD

**Issue by RvdHout** [DigitalRuby/IPBan#208]
I will try to summarize what i tried, the goal is to **only** allow certain ip addresses to connect over RDP
I got 2 static ip addresses that should be able to access the system over RDP and 1 dyndns dns name that should be able to access the system over RDP

```
<add key="Whitelist" value="192.168.0.0/16,{STATIC IPADDRESS 1},{STATIC IPADDRESS 2}, {DYNDNS HOSTNAME}">
<add key="Blacklist" value="0.0.0.0/0"> 
```

adding 0.0.0.0/0 to Blacklist key seems to cause a crash, eg:
```
2022-07-04 12:41:44.6361|ERROR|IPBan|Error Exception: System.Runtime.InteropServices.COMException (0x8007000D): The data is invalid. (0x8007000D)
   at DigitalRuby.IPBanCore.Windows.COM.INetFwRule.set_RemoteAddresses(String value)
   at DigitalRuby.IPBanCore.IPBanWindowsFirewall.GetOrCreateRule(String ruleName, String remoteIPAddresses, NetFwAction action, IEnumerable`1 allowedPorts)
```

0.0.0.0/0 isn't accepted by Windows firewall (when manually inserted) as well, so i think it is fair to say what i am trying simply is not possible?
![image](https://user-images.githubusercontent.com/13403301/177139665-708b5c90-f03c-4f33-9ce6-18359c32a032.png)

**Comment by jjxtra** [comment]
I don't think you need to use ipban rules for this. Just create a single Window firewall for rdp (or modify the existing rule) to only include the ip addresses you want.

**Comment by RvdHout** [comment]
Yep, you are right i solved this by updating the windows firewall rule with as powershell script that is been ran from task scheduler every 15 minutes , I'll post it here if anyone is interested and completeness

```
$static = @("LocalSubnet","{STATIC IPADDRESS 1}","{STATIC IPADDRESS 2}")
# obtain IP address of the hostname
$dynamic = [System.Net.Dns]::GetHostAddresses("{DYNDNS HOSTNAME}").IpAddressToString
if (-not [string]::IsNullOrEmpty($dynamic)) {
	$iplist = $static + $dynamic
}
else {
	$iplist = $static
}
Set-NetFirewallRule -DisplayName "Remote Desktop - User Mode (UDP-In)" -RemoteAddress $iplist
Set-NetFirewallRule -DisplayName "Remote Desktop - User Mode (TCP-In)" -RemoteAddress $iplist
```
