### ISSUE TITLE
Silent install

### ISSUE THREAD

**Issue by funnymomo** [DigitalRuby/IPBan#210]
Hi.. I am trying to install this in a AWS machine.. and I think the PS script is causing a issue. Can you update the script so that it takes an argument for silent install - so that it doesnt open up the notepad after install ?

**Comment by jjxtra** [comment]
https://github.com/DigitalRuby/IPBan/blob/master/IPBanCore/Windows/Scripts/install_latest.ps1

**Comment by funnymomo** [comment]
wow..thanks.. this was fast..
