### ISSUE TITLE
block ip address using dns name not working

### ISSUE THREAD

**Issue by fhm20** [DigitalRuby/IPBan#213]
Hello

I'm testing the  default rule for mysql/mariadb

      <Group>
        <Source>MySQL</Source>
        <Keywords>0x80000000000000</Keywords>
        <Path>Application</Path>
        <FailedLoginThreshold>0</FailedLoginThreshold>
        <Expressions>
          <Expression>
            <XPath>//Provider[@Name='MySQL' or @Name='MariaDB']</XPath>
            <Regex></Regex>
          </Expression>
          <Expression>
            <XPath>//Data</XPath>
            <Regex>
              <![CDATA[
                Access denied for user '?(?<username>[^']+)'@'(?<ipaddress>[^']+)'
              ]]>
            </Regex>
          </Expression>
        </Expressions>
      </Group>

The windows event log viewer shows 
Access denied for user 'root'@'server.domain.com' (using password: YES)

The IPBan log shows
2022-09-07 15:03:05.9915|INFO|IPBan|Parsing as IP failed for server.domain.com, info: MySQL. Checking dns...
2022-09-07 15:03:05.9935|INFO|IPBan|Dns result 'server.domain.com' = 'XXX.XXX.XXX.XXX'

The dns result is correct and the ip is valid, but IPBan does not create the rule in the firewall. 

I'm using Windows server 2012/2019  and mariadb 10.5.9

Thanks

**Comment by jjxtra** [comment]
Fixed in 3ad29f43294e25444b9e573ec62a1761e3297460

Please re-download the latest 1.8.0 release and let me know if you see expected behavior.

**Comment by fhm20** [comment]
It works perfect!
Thanks
