### ISSUE TITLE
I made it with beginner skills. Manual installation `IPBan`

### ISSUE THREAD

**Issue by oklokl** [DigitalRuby/IPBan#226]
https://github.com/DigitalRuby/IPBan/releases
Download the file.
The file should be in your Downloads folder.
```
md "%USERPROFILE%\Downloads\IPBan"
cd "%USERPROFILE%\Downloads\IPBan"
for /f "delims=" %a in ('dir /a-d /b /o /s "%USERPROFILE%\Downloads\IPBan-Windows-x64*.zip"') do (tar -zxvf "%a" -C ".") 
xcopy "%USERPROFILE%\Downloads\IPBan" "%ProgramFiles%\IPBan\" /e /h /k
auditpol.exe /set /category:"{69979849-797A-11D9-BED3-505054503030}" /success:enable /failure:enable
auditpol.exe /set /category:"{69979850-797A-11D9-BED3-505054503030}" /success:enable /failure:enable
sc.exe create IPBAN type= own start= auto binPath= "%ProgramFiles%\IPBan\DigitalRuby.IPBan.exe" DisplayName= "IPBan Service"
sc.exe description IPBAN "Automatically builds firewall rules for abusive login attempts: https://github.com/DigitalRuby/IPBan"
sc.exe failure IPBAN reset= 9999 actions= "restart/60000/restart/60000/restart/60000"
sc.exe start IPBAN
net stop IPBAN
cd "%ProgramFiles%\IPBan" && tar -cvzf "%ProgramFiles%\IPBan\ipban-config.zip" "ipban.config"
notepad "%ProgramFiles%\IPBan\ipban.config"
net start IPBAN
```

These are my edits.
Register after 5 failed login attempts
search word `FailedLoginAttemptsBeforeBan`
`<add key="FailedLoginAttemptsBeforeBan" value="5"/>`

Block Date Time 2 Days `BanTime`
`<add key="BanTime" value="02:00:00:00"/>`

2 days from the date of removal after blocking `ExpireTime`
`<add key="ExpireTime" value="02:00:00:00"/>`

FailedLoginRegex failed login regex `FailedLoginRegex`
`<Source>IPBanCustom</Source>`
`<FailedLoginThreshold>1</FailedLoginThreshold>`

echo Block login attempts "https://support.forpsi.hu/kb/a612/windows-remote-desktop-protocol-rdp-bejelentkezesi-hiba-elharitas.aspx "
echo Conclusion that this seems to be important. Block RDP Blocking from 1st If wrong, set to 6, block 6 times wrong
"`* WINDOWS ONLY *`"  `WINDOWS ONLY`
`<FailedLoginThreshold>6</FailedLoginThreshold>`

`cd "%ProgramFiles%\IPBan" && tar -cvzf "%ProgramFiles%\IPBan\ipban-config2.zip" "ipban.config"`
save again as

echo run
`net start IPBAN`

Other permission cycles
echo Problem turning on IPBan to restrict permission. 
add
```
icacls "%ProgramFiles%\IPBan" 
takeown /F "%ProgramFiles%\IPBan" /A /r
icacls "%ProgramFiles%\IPBan" /grant Administrators:F /t
icacls "%ProgramFiles%\IPBan" /setintegritylevel H /t
icacls "%ProgramFiles%\IPBan" /deny "Guest:F" "*S-1-5-32-546:F" "*S-1-0-0:F" "*S-1-5-7:F" /t
icacls "%ProgramFiles%\IPBan" /setowner "NT SERVICE\TrustedInstaller" /t
icacls "%ProgramFiles%\IPBan" /grant:r Administrators:RX /t
icacls "%ProgramFiles%\IPBan" 
```
.

.

remove
```
takeown /F "%ProgramFiles%\IPBan" /A /r
icacls "%ProgramFiles%\IPBan" /grant Administrators:F /t
icacls "%ProgramFiles%\IPBan" /remove "*S-1-5-2" /t
icacls "%ProgramFiles%\IPBan" /setowner "NT SERVICE\TrustedInstaller" /t
icacls "%ProgramFiles%\IPBan" /grant:r Administrators:RX /t
icacls "%ProgramFiles%\IPBan" 
```

.

.

when editing "ipban.config"
```
takeown /F "%ProgramFiles%\nlog.config.config" /A
takeown /F "%ProgramFiles%\IPBan\ipban.config" /A
icacls "%ProgramFiles%\IPBan\nlog.config" /grant Administrators:F
icacls "%ProgramFiles%\IPBan\ipban.config" /grant Administrators:F
net stop IPBAN
notepad "%ProgramFiles%\IPBan\ipban.config"
net start IPBAN
```

I don't speak English, so I used Google Translate.

Are the things I wrote correct?

additional i
In case of delayed auto.
working too slow
changed to `auto`

`sc config IPBAN start=auto`

**Comment by jjxtra** [comment]
There is a power shell script for install : https://github.com/DigitalRuby/IPBan/IPBanCore/Windows/Scripts/install_latest.ps1
