### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by lKamuz** [DigitalRuby/IPBan#229]
Hello, I am running a windows server 2019 RDP, and in the logfiles I see the following logging error, and in the windows event viewer I do not see such error.
2022-11-17 16:46:24.2351|WARN|IPBan|Login failure: 178.32.197.95, , RDP, 1, 14

**Comment by jjxtra** [comment]
Which RDP parts of event viewer are you looking in? Here are the relevant paths from the default config:

- <Keywords>0x8010000000000000</Keywords><Path>Security</Path>
- <Keywords>0x4000000000000000</Keywords><Path>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Path>

Do you see that ip in the event viewer around that timestamp in either of those paths?

**Comment by jjxtra** [comment]
Looks like that is the failed login :)
