### ISSUE TITLE
ipban.sqlite;Cache=Shared; What is this?. can i block it?

### ISSUE THREAD

**Issue by oklokl** [DigitalRuby/IPBan#230]
Initializing IPBan database at Data Source=C:\Program Files\IPBan\ipban.sqlite;Cache=Shared;
There is this message in the log.

I don't want to share.

Is my login being shared?.
I am using google translator. sorry.

`CachedLogonsCount /t REG_SZ /d 0`
I don't want to share.

But recently cache login type 11
It was recorded in the Windows log.

I blocked it as much as possible to avoid cache login.
I'm also not using auto-login.

[logfile.txt](https://github.com/DigitalRuby/IPBan/files/10095864/logfile.txt)
[11.zip](https://github.com/DigitalRuby/IPBan/files/10095866/11.zip)
These are my log files and settings.
My IP is covered with a '***' mark.
[cfg.zip](https://github.com/DigitalRuby/IPBan/files/10095914/cfg.zip)
Other information My computer `secedit` settings.

And I `ipban` installed the program and login type 11 is not being logged.

Speaking of cache sharing, how can I block it?
I haven't made any other special settings.

IPBan 1.8.0 

Microsoft Windows10 64bit home kr insider [Version 10.0.19045.2251]

The program works well.
thank you.

If you want new features, please consider donating. 

For new ideas and feature requests, please use the discussions area here: https://github.com/DigitalRuby/IPBan/discussions/categories/ideas

Thank you.

Jeff Johnson

**Comment by jjxtra** [comment]
Cache shared is just a way that sqlite manages internal memory
