### ISSUE TITLE
Update documentation on maximum BanTime

### ISSUE THREAD

**Issue by gfmaster** [DigitalRuby/IPBan#234]
Hello, 

Explanation on maximum BanTime is inconsistent.

- What happened to me
I tried setting BanTime to "07:00:00:00,31:00:00:00,92:00:00:00,365:00:00:00". Of course it exceeded max bantime, and keep getting the following error: "Multiple time spans must be in strictly ascending order. This is not the case for 90.00:00:00. Ignoring this entry."

- What's wrong
How IPBan actually works and documentations I can find are not same, thus creating confusion.

- IPBan's Actual behaviour : setting BanTime to 00:00:00:00 equals maximum bantime of 90:00:00:00

- Configuration entry on github wiki : https://github.com/DigitalRuby/IPBan/wiki/Configuration
"BanTime - the time to ban an ip address in DD:HH:MM:SS format (days, hours, minutes and seconds, 0 padded). 00:00:00:00 to ban forever. Be aware that banning forever will constantly grow the firewall rules, so watch out for performance and/or memory issues."

- Comment section from ipban.config
"00:00:00:00 for max duration.", not specifying what actual maximum duration is.

I'm fine with 90 days max ban duration, but it would be much nicer if that restriction is explicitly written in wiki and config.

Thank you

**Comment by jjxtra** [comment]
I've updated the docs
