### ISSUE TITLE
Running fine on W11 22H2 but not picking up failed RDP attempts 

### ISSUE THREAD

**Issue by florisjan78** [DigitalRuby/IPBan#239]
As the tile says. This is what happens in the event [viewer:.]( https://pastebin.com/9rfHaBdM) If I look in the config I see keywords "0x80000000000000" and "0x8010000000000000" but they don't seem to occur in the event log.

**Comment by jjxtra** [comment]
If you can figure out why the ip address is not logged in this event that is why ipban is not picking up the ip address. Is it an internal ip address by chance?

**Comment by jjxtra** [comment]
That's probably it, you need to set the option to process internal ip address to true instead of false.

**Comment by florisjan78** [comment]
It is probably a local address as it is being forwarded by the router. What makes you say it is not being logged?
I have changed it to <add key="ProcessInternalIPAddresses" value="true"/> and restarted, nothing has changed.
