### ISSUE TITLE
Running fine on W11 22h2 but not responding to RDP fails

### ISSUE THREAD

**Issue by florisjan78** [DigitalRuby/IPBan#240]
Although this should no longer be necessary I have tried [fixing the NTLM](https://howtofix.guide/ntlm-authentication-deactivate/). This is what a [failed attempt] https://pastebin.com/9rfHaBdMl) looks like in the event log. The event that seems to be required to trigger an RDP fail (0x8010000000000000) does not appear in the log.

**Comment by florisjan78** [comment]
Sorry I missed the comments on my previous post and thought it had disappeared

**Comment by florisjan78** [comment]
Reopening this because your solution did not work.

It is probably a local address as it is being forwarded by the router. What makes you say it is not being logged?
I have changed it to add key="ProcessInternalIPAddresses" value="true"/ and restarted, nothing has changed.

**Comment by jjxtra** [comment]
Pastebin was deleted. If you have event viewer xml with an ip that you believe should be picked up by ipban but was not, please post it here. Feel free to mask out sensitive data.

**Comment by florisjan78** [comment]
I now realize that this can't work with port forwarding because it is impossible to know the original client ip address. The client address is the router:  <Data Name="ClientIP">192.168.178.1:54816</Data> and unfortunately when connecting via 4G I can't use IPv6.

`Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      148
Task Category: RemoteFX module
Level:         Information
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
Channel rdplic has been closed between the server and the client on transport tunnel: 0.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>148</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>4</Task>
    <Opcode>17</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3587688Z" />
    <EventRecordID>2407</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="8220" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="ChannelName">rdplic</Data>
    <Data Name="TunnelID">0</Data>
  </EventData>
</Event>

Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      148
Task Category: RemoteFX module
Level:         Information
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
Channel Microsoft::Windows::RDS::CoreInput has been closed between the server and the client on transport tunnel: 1.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>148</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>4</Task>
    <Opcode>17</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3587591Z" />
    <EventRecordID>2406</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="8220" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="ChannelName">Microsoft::Windows::RDS::CoreInput</Data>
    <Data Name="TunnelID">1</Data>
  </EventData>
</Event>

Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      148
Task Category: RemoteFX module
Level:         Information
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
Channel rdpcmd has been closed between the server and the client on transport tunnel: 0.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>148</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>4</Task>
    <Opcode>17</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3587566Z" />
    <EventRecordID>2405</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="8220" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="ChannelName">rdpcmd</Data>
    <Data Name="TunnelID">0</Data>
  </EventData>
</Event>

Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      148
Task Category: RemoteFX module
Level:         Information
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
Channel rdpinpt has been closed between the server and the client on transport tunnel: 0.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>148</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>4</Task>
    <Opcode>17</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3587535Z" />
    <EventRecordID>2404</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="8220" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="ChannelName">rdpinpt</Data>
    <Data Name="TunnelID">0</Data>
  </EventData>
</Event>

Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      145
Task Category: RemoteFX module
Level:         Information
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
During this connection, server has not sent data or graphics update for 0 seconds (Idle1: 0, Idle2: 0).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>145</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>4</Task>
    <Opcode>19</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3587485Z" />
    <EventRecordID>2403</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="8220" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="IdleSeconds">0</Data>
    <Data Name="IdleSeconds1">0</Data>
    <Data Name="IdleSeconds2">0</Data>
  </EventData>
</Event>

Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      102
Task Category: RemoteFX module
Level:         Information
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
The server has terminated main RDP connection with the client.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>102</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>4</Task>
    <Opcode>17</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3587461Z" />
    <EventRecordID>2402</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="8220" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
  </EventData>
</Event>

Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      72
Task Category: RemoteFX module
Level:         Information
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
Interface method called: OnDisconnected
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>72</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>4</Task>
    <Opcode>13</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3587251Z" />
    <EventRecordID>2401</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="8220" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="MethodName">OnDisconnected</Data>
  </EventData>
</Event>

Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      142
Task Category: RemoteFX module
Level:         Warning
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
TCP socket READ operation failed, error 64
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>142</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>4</Task>
    <Opcode>15</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3583548Z" />
    <EventRecordID>2400</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="9400" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="error">64</Data>
  </EventData>
</Event>

Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      226
Task Category: RemoteFX module
Level:         Warning
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
RDP_TCP: An error was encountered when transitioning from StateUnknown in response to Event_Disconnect (error code 0x80070040).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>226</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>4</Task>
    <Opcode>19</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3583355Z" />
    <EventRecordID>2399</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="2192" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="StateTransition">RDP_TCP</Data>
    <Data Name="PreviousState">23</Data>
    <Data Name="PreviousStateName">StateUnknown</Data>
    <Data Name="NewState">21</Data>
    <Data Name="NewStateName">StateDisconnected</Data>
    <Data Name="Event">43</Data>
    <Data Name="EventName">Event_Disconnect</Data>
    <Data Name="ErrorCode">0x80070040</Data>
  </EventData>
</Event>

Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      143
Task Category: RemoteFX module
Level:         Warning
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
TCP socket WRITE operation failed, error 64
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>143</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>4</Task>
    <Opcode>15</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3583180Z" />
    <EventRecordID>2398</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="2192" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="error">64</Data>
  </EventData>
</Event>

Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      141
Task Category: RemoteFX module
Level:         Information
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
PerfCounter session started with instance ID 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>141</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>4</Task>
    <Opcode>11</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3091915Z" />
    <EventRecordID>2397</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="10544" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="InstanceID">0</Data>
  </EventData>
</Event>

Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      72
Task Category: RemoteFX module
Level:         Information
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
Interface method called: SendPolicyData
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>72</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>4</Task>
    <Opcode>13</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3089887Z" />
    <EventRecordID>2396</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="10544" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="MethodName">SendPolicyData</Data>
  </EventData>
</Event>

Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      72
Task Category: RemoteFX module
Level:         Information
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
Interface method called: PrepareForAccept
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>72</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>4</Task>
    <Opcode>13</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3089838Z" />
    <EventRecordID>2395</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="10544" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="MethodName">PrepareForAccept</Data>
  </EventData>
</Event>

Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      65
Task Category: RemoteFX module
Level:         Information
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
Connection RDP-Tcp#0 created 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>65</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>4</Task>
    <Opcode>13</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3084050Z" />
    <EventRecordID>2394</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="8228" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="ConnectionName">RDP-Tcp#0</Data>
  </EventData>
</Event>

Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          18-Jan-23 1:31:35
Event ID:      131
Task Category: RemoteFX module
Level:         Information
Keywords:      
User:          NETWORK SERVICE
Computer:      Desktop-RickAstley
Description:
The server accepted a new TCP connection from client 192.168.178.1:54816.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139c61b-b549-4251-8ed3-RickAstley}" />
    <EventID>131</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>4</Task>
    <Opcode>15</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-18T00:31:35.3033362Z" />
    <EventRecordID>2393</EventRecordID>
    <Correlation ActivityID="{f420298e-eb91-4034-840d-8601f6850000}" />
    <Execution ProcessID="1268" ThreadID="8244" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>Desktop-RickAstley</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="ConnType">TCP</Data>
    <Data Name="ClientIP">192.168.178.1:54816</Data>
  </EventData>
</Event>`

**Comment by florisjan78** [comment]
[new pastebin](https://pastebin.com/9rfHaBdM)

**Comment by jjxtra** [comment]
I think there is nothing that can be done here. If you can remove the port forward and allow direct machine access then the software can read remote ip from event viewer.
