### ISSUE TITLE
IBAN - Blocking requests IP when VNC sends ICMP requests

### ISSUE THREAD

**Issue by carlosgalveias** [DigitalRuby/IPBan#247]
Hi, I am kind of new to IPBAN and I am trying to configure it on a cloud windows 2016 server. We also have VNC on a non standard port (7943). However the vnc is making ICMP errors in the system event log and that is triggering the RDP rule. 

Is there a way to ignore that? The event that is triggering is something like this:
`<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'>
    <System>
      <Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-A5BA-3E3B0328C30D}' />
      <EventID>5152</EventID>
      <Version>0</Version>
      <Level>0</Level>
      <Task>12809</Task>
      <Opcode>0</Opcode>
      <Keywords>0x8010000000000000</Keywords>
      <TimeCreated SystemTime='2023-03-14T00:12:30.209104700Z' />
      <EventRecordID>844370</EventRecordID>
      <Correlation />
      <Execution ProcessID='4' ThreadID='604' />
      <Channel>Security</Channel>
      <Computer>d-1678708092997.redacted.com</Computer>
      <Security />
    </System>
    <EventData><Data Name='ProcessId'>0</Data><Data Name='Application'>-</Data><Data Name='Direction'>%%14593</Data><Data Name='SourceAddress'>158.177.43.8</Data><Data Name='SourcePort'>0</Data><Data Name='DestAddress'>94.62.133.18</Data><Data Name='DestPort'>0</Data><Data Name='Protocol'>1</Data><Data Name='FilterRTID'>68186</Data><Data Name='LayerName'>%%14601</Data><Data Name='LayerRTID'>32</Data></EventData>
  </Event>

and

<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'>
    <System>
      <Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-A5BA-3E3B0328C30D}' />
      <EventID>5152</EventID>
      <Version>0</Version>
      <Level>0</Level>
      <Task>12809</Task>
      <Opcode>0</Opcode>
      <Keywords>0x8010000000000000</Keywords>
      <TimeCreated SystemTime='2023-03-14T00:12:30.209072000Z' />
      <EventRecordID>844369</EventRecordID>
      <Correlation />
      <Execution ProcessID='4' ThreadID='604' />
      <Channel>Security</Channel>
      <Computer>d-1678708092997.redacted.com</Computer>
      <Security />
    </System>
    <EventData><Data Name='ProcessId'>0</Data><Data Name='Application'>-</Data><Data Name='Direction'>%%14592</Data><Data Name='SourceAddress'>94.62.133.18</Data><Data Name='SourcePort'>52078</Data><Data Name='DestAddress'>158.177.43.8</Data><Data Name='DestPort'>7943</Data><Data Name='Protocol'>17</Data><Data Name='FilterRTID'>68174</Data><Data Name='LayerName'>%%14597</Data><Data Name='LayerRTID'>13</Data></EventData>
  </Event>`

This eventually blocks my ip (94.62.133.18) 
Is there a way to ignore port 7943 or protocol 1 (icmp) ?

**Comment by jjxtra** [comment]
You could add an allow rule in windows firewall for that port or whitelist your ip.

**Comment by carlosgalveias** [comment]
Hi @jjxtra , the problem is that we don't know the IP addresses, this will eventually be installed in several machines with different users using VNC and/or RDP.

**Comment by jjxtra** [comment]
Sounds like allow rule for that port in Windows firewall is the way to go, I don't think IPBan can help you in this case without some work to the codebase.

**Comment by carlosgalveias** [comment]
We have the rule, however IPBAN blocks the IP so... that doesn't work.
Is there a way to force the RDP to just detect the RDP port?
The expressions are a 'OR' , it doesn't have to match all expressions for a rule to work?
