### ISSUE TITLE
Com Exception errors?

### ISSUE THREAD

**Issue by kimboslice99** [DigitalRuby/IPBan#251]
This has begun appearing in my logs... unsure how to rectify? I have tried deleting the ipban.sqlite database but the error still occurs
```
2023-03-21 15:34:05.4118|ERROR|IPBan|Error Exception: System.Runtime.InteropServices.COMException (0xD000000D): 0xD000000D
   at DigitalRuby.IPBanCore.Windows.COM.INetFwRule.set_RemoteAddresses(String value)
   at DigitalRuby.IPBanCore.IPBanWindowsFirewall.GetOrCreateRule(String ruleName, String remoteIPAddresses, NetFwAction action, IEnumerable`1 allowedPorts)
```

**Comment by jjxtra** [comment]
Sounds like Windows Firewall is having issues. I would suggest to uninstall ipban and then go into Windows Firewall and remove all IPBan entries. Then you can re-install ipban.

**Comment by kimboslice99** [comment]
I already tried removing all IPBan_ rules and updated to 1.8.1, same issue...

**Comment by jjxtra** [comment]
Can you try on another Windows server? Just trying to rule out a code issue vs issue on your server.

**Comment by jjxtra** [comment]
https://www.digitalcitizen.life/restore-windows-firewall-defaults/

**Comment by kimboslice99** [comment]
Okay I've figured out how to reproduce this issue, I had a whitelist with ::1 in it (generated by php + mysql), and this causes the error mentioned

The error only occurs if the whitelist is loaded from a url like http://127.0.0.1/IP.php, if you simply add ::1 to the whitelist no error occurs

**Comment by jjxtra** [comment]
So the `::1` was in a firewall uri rule?

**Comment by kimboslice99** [comment]
It was in `<add key="Whitelist" value="" />`

So the config looked something like 
```
<add key="Whitelist" value="
    http://127.0.0.1/IP.php
" />
```

**Comment by kimboslice99** [comment]
Ya exactly, with ::1 removed the error goes away

My exact process of reproducing, create IP.php
```php
<?php
header('Content-Type: text/plain');
print '::1';
```
then run `php -S 127.0.0.1:8000` in the folder with IP.php and add the address to the whitelist

IPBan now throws the error

**Comment by jjxtra** [comment]
I guess I could filter ::1 in the whitelist? Does it also happen with 127.0.0.1?

**Comment by kimboslice99** [comment]
Nope doesnt happen with 127.0.0.1 or localhost, only ::1

**Comment by jjxtra** [comment]
Do you think it's safe to ignore ::1 for any ip address sent to the firewall?

**Comment by kimboslice99** [comment]
I'd think so, interestingly, windows firewall doesnt allow IPv6 loopback addresses, but does allow IPv4 loopback addresses

**Comment by jjxtra** [comment]
Agreed, I will change the win firewall code to do so

**Comment by kimboslice99** [comment]
Awesome, glad I could help identify this issue

A little off topic, but, my entire journey into the world of coding started with you sending me that "Lets have an argument" link about powershell scripting, and since then I have played a **lot** with php and more recently C#, so I just wanted to give a huge thanks for that
