### ISSUE TITLE
I succeeded for the first time. Thank you so much.

### ISSUE THREAD

**Issue by oklokl** [DigitalRuby/IPBan#252]
I am a Windows 10 Home user. Even though it's usually used for Pro or Server, I love and want to use the IPBan program :)

Today, after several years of trying, I finally succeeded in installing it. I also manually installed gpedit.msc.

I managed to succeed by adding the following text, which I asked an AI to help me with. It turns out I had to register this in order for it to work:

REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft.NETFramework\v4.0.30319" /v "SchUseStrongCrypto" /t REG_DWORD /d 1 /f
REG ADD "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client" /v "DisabledByDefault" /t REG_DWORD /d 0 /f
REG ADD "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client" /v "Enabled" /t REG_DWORD /d 1 /f
REG ADD "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server" /v "DisabledByDefault" /t REG_DWORD /d 0 /f
REG ADD "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server" /v "Enabled" /t REG_DWORD /d 1 /f
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft.NETFramework\v4.0.30319" /v "SystemDefaultTlsVersions" /t REG_DWORD /d 1 /f
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft.NETFramework\v4.0.30319" /v "SchUseStrongCrypto" /t REG_DWORD /d 1 /f

Today, I also asked an AI for help in saving a file with the date, time, and second. I used the following code:

powershell -Command "& { $datetime = (Get-Date).ToString('yyyyMMddHHmmss'); Compress-Archive -Path '%ProgramFiles%\IPBan\ipban.config' -DestinationPath ('%ProgramFiles%\IPBan\ipbanconfig' + $datetime + '.zip'); }"

I'm just a beginner with computers, so it took me a long time to execute everything correctly. It's a bit disappointing, but I'm still happy. It would be great to have a guide for home users like me to be able to install it.

Fortunately, gpedit.msc wasn't difficult to install.

Activating NTLM was a bit difficult for me:

reg add HKEY_LOCAL_MACHINE\System\CurrentControlSet\control\LSA\MSV1_0 /v RestrictReceivingNTLMTraffic /t REG_DWORD /d 2 /f

Thank you, by the way. It's been successfully registered in wf.msc.

Lastly, I don't quite understand "Initialized event viewer with query string." Also, since I don't use RDP, did I block something? I see IP addresses 110 and 140.
Oh, IP 110 is GitHub. The rest are from me logging into a Korean Naver website with IP 140.. :) Whew, I was nervous.

Anyway, thank you.
![1](https://user-images.githubusercontent.com/1571600/227790027-c0e38e6d-ff07-4cda-a7b1-c966a5215277.png)

![2](https://user-images.githubusercontent.com/1571600/227790462-261dce20-a1ed-4525-a64f-8dcb1b2dc8e5.png)

**Comment by jjxtra** [comment]
Glad you got it figured out. AI is in it's infancy and already a magnificent complement to the human brain.
