### ISSUE TITLE
Log parse and counter

### ISSUE THREAD

**Issue by be4i** [DigitalRuby/IPBan#257]
Hello,

I am parsing hMail log and looking for 550 Unknow user spam that checks what mailbox exists.
That is my regex:
 `^\"SMTPD\"\s[0-9]+\s+[0-9]+\s\"(?<timestamp>[^\"]+)\"\s+\"(?<ipaddress>[^\"]+)\"\s+\"SENT:\s(?<log>550)\sUnknow[^\n]*`

Spam comes in batches, in one session the spammer checks 20-30 mailboxes like this:
"SMTPD"	16948	52367	"2023-05-28 20:42:43.846"	"IP"	"RECEIVED: RCPT TO:<---->"
"SMTPD"	16948	52367	"2023-05-28 20:42:43.846"	"IP"	"SENT: 550 Unknown user"
"SMTPD"	3128	52367	"2023-05-28 20:42:43.846"	"IP"	"RECEIVED: RCPT TO:<---->"
"SMTPD"	3128	52367	"2023-05-28 20:42:43.846"	"IP"	"SENT: 550 Unknown user"
"SMTPD"	3128	52367	"2023-05-28 20:42:43.846"	"IP"	"RECEIVED: RCPT TO:<---->"
"SMTPD"	3128	52367	"2023-05-28 20:42:43.846"	"IP"	"SENT: 550 Unknown user"
"SMTPD"	3128	52367	"2023-05-28 20:42:43.846"	"IP"	"RECEIVED: RCPT TO:<---->"
"SMTPD"	3128	52367	"2023-05-28 20:42:43.861"	"IP"	"SENT: 550 Unknown user"
"SMTPD"	13608	52367	"2023-05-28 20:42:43.861"	"IP"	"RECEIVED: RCPT TO:<---->"
"SMTPD"	13608	52367	"2023-05-28 20:42:43.861"	"IP"	"SENT: 550 Unknown user"
"SMTPD"	3128	52367	"2023-05-28 20:42:43.861"	"IP"	"RECEIVED: RCPT TO:<---->"
"SMTPD"	3128	52367	"2023-05-28 20:42:43.861"	"IP"	"SENT: 550 Unknown user"
"SMTPD"	13608	52367	"2023-05-28 20:42:43.861"	"IP"	"RECEIVED: RCPT TO:<---->"
"SMTPD"	13608	52367	"2023-05-28 20:42:43.861"	"IP*"	"SENT: 550 Unknown user"
"SMTPD"	16948	52367	"2023-05-28 20:42:43.861"	"IP"	"RECEIVED: RCPT TO:<---->"
"SMTPD"	16948	52367	"2023-05-28 20:42:43.861"	"IP"	"SENT: 550 Unknown user"
"SMTPD"	16948	52367	"2023-05-28 20:42:43.861"	"IP"	"RECEIVED: RCPT TO:<----->"
"SMTPD"	16948	52367	"2023-05-28 20:42:43.861"	"IP"	"SENT: 550 Unknown user"

But IPBan count only 4 login failures, in reality they are 20-30, is this intended or i am doing something wrong?

**Comment by jjxtra** [comment]
You can change the min time between logins to 0.

**Comment by be4i** [comment]
Thanks for your fast replay, is there any drawbacks to setting it to zero? why is not zero by default?

**Comment by jjxtra** [comment]
Because some single failed logins may be counted by multiple scans rapidly, locking out legit users who just failed one time in reality.

**Comment by be4i** [comment]
Ok, thank you for the info.
