### ISSUE TITLE
Whitelist Port 25

### ISSUE THREAD

**Issue by salusalpha** [DigitalRuby/IPBan#259]
Dear Jeff

Please let me know how to whitelist port 25. 

Thanks

**Comment by jjxtra** [comment]
You could try adding a windows firewall rule to inbound port 25 as allow. If that doesn't work I'll have to add an allowed ports functionality.

**Comment by salusalpha** [comment]
is this the correct way how to add to config?

<add key="FirewallRules" value="
SMTP_25;allow;0.0.0.0/1;25;^(?:(?!Windows).)+$
SMTP_143;allow;0.0.0.0/1;143;^(?:(?!Windows).)+$
SMTP_587;allow;0.0.0.0/1;587;^(?:(?!Windows).)+$
"/>

**Comment by jjxtra** [comment]
I'm hoping windows firewall will just work. If not I'll have to add a setting.

**Comment by jjxtra** [comment]
That looks correct
