### ISSUE TITLE
MailEnable = Sending mails without authentication

### ISSUE THREAD

**Issue by carlhoogstoel** [DigitalRuby/IPBan#260]
Hello,

I was wondering if it was possible to ban IP's if they are trying to send mai lto non local e=mail addresses.

The log entries look like this:

"06/20/23 06:12:50	SMTP-IN	F97C625D979F4C59B928F5A02B4B99E9.MAI	1448	220.246.64.193	RCPT	RCPT TO:<sam@jylgpgdtf.c4consulting.be>	503 This mail server requires authentication when attempting to send to a non-local e-mail address. Please check your mail client settings or contact your administrator to verify that the domain or address is defined for this server.	235	0"

Thx for the great tool!

**Comment by jjxtra** [comment]
The mail enable failed login regex should be able to be adjusted for this

**Comment by jjxtra** [comment]
Resolved in f663c9674cbed1d115c637d899c1f9e8d16e6d5f, 2.0.0 build updated
