### ISSUE TITLE
firewalld

### ISSUE THREAD

**Issue by kevmza01** [DigitalRuby/IPBan#266]
Hi there,

firstly, thank you very much for this product. For the Linux version I am on Debian and I see the install file for 1.9.0 seems to now include firewalld. 

I use UFW on my servers and it breaks it by installing firewalld. Can I use it with UFW?
Another question, when using firewalld and enabling the emergingthreats or using ipthreat.net in firewalluri it seems to break the config of firewalld. I am getting this in the logs: |ERROR|IPBan|Process firewall-cmd --reload had exit code 13

I use debian:  5.10.0-23-amd64 #1 SMP Debian 5.10.179-2 (2023-07-14) x86_64 GNU/Linux

Thanks.

**Comment by jjxtra** [comment]
UFW is not supported, so you would have to rollback to 1.8.1 with iptables if that is compatible with UFW, or wait until UFW support is added.
