### ISSUE TITLE
Ban time not being applied

### ISSUE THREAD

**Issue by carlhoogstoel** [DigitalRuby/IPBan#273]
Hello,

I think I'm missing something. In the config I set the bantime to always like this:

`
    <add key="BanTime" value="00:00:00:00"/>`

But when I look at the logs, I can see that they are getting unbanned.

`2023-10-02 09:19:52.4636|INFO|DigitalRuby.IPBanCore.Logger|Firewall entries updated: 211.93.42.16
2023-10-02 09:23:53.2753|WARN|DigitalRuby.IPBanCore.Logger|Un-banning ip address 121.202.195.22, ban expired`

Then when I look at the data, you can see that the ban is only for 3 months:

`	124.152.181.85	1696230063356	2	1696230063349	0	1704006063349		MailEnable`

Is there something I am doing wrong?

**Comment by jjxtra** [comment]
The latest 1.9.0 update changed the upper bounds to 9999 days.

**Comment by carlhoogstoel** [comment]
My bad. Thank you.
