### ISSUE TITLE
 IPBan 1.8.1 uses A LOT of ressources each 10-15 seconds for no reason.

### ISSUE THREAD

**Issue by wazerstar** [DigitalRuby/IPBan#278]
I recorded a little video showing how it behaves every XX seconds

https://streamable.com/amvn2u

Can't stop thinking if its because of the firewall block list?

I think it would be better to have a txt file to run through if possible?

https://streamable.com/w5w5k1

**Comment by jjxtra** [comment]
How many ips?

**Comment by jjxtra** [comment]
Looks like hundreds of thousands. You have two options. Use server 2022 or use ipban pro. Windows firewall is dog slow on earlier windows versions.

**Comment by wazerstar** [comment]
> Looks like hundreds of thousands. You have two options. Use server 2022 or use ipban pro. Windows firewall is dog slow on earlier windows versions.

How to check that

**Comment by jjxtra** [comment]
IPBan Pro has a 30 day free trial:

https://ipban.com/products/ipban-pro-personal-free-trial-download/
https://ipban.com/products/ipban-pro-datacenter-free-trial-download/
