### ISSUE TITLE
One line Installer on Ubuntu makes the entire machine go offline

### ISSUE THREAD

**Issue by zanek** [DigitalRuby/IPBan#280]
I did a sudo -i; bash <(wget -qO- https://raw.githubusercontent.com/DigitalRuby/IPBan/master/IPBanCore/Linux/Scripts/Install.sh)

It ran through some steps and  started a progress bar with '===' and then my SSH session dropped, and my entire server wont allow a connection now !!!

The install works great on Windows, but this is horrible on Linux (using Ubuntu 22.04 )

**Comment by jjxtra** [comment]
Huh. I'm using it on my Linux boxes.

**Comment by zanek** [comment]
Do you know why installing IPBan would cause this  ? This machine has been running with no issues for a year until I used IPBan.

 I have a web interface to get to a KVM directly on the machine  but all incoming/outgoing requests return "Temporary failure in name resolution"

I've been trying to frantically determine what it broke

**Comment by zanek** [comment]
Alright, I found the issue.  IPBan had set all INCOMING to DROP in IPTABLES , during the install . I made do accept and everything is working mostly

**Comment by jjxtra** [comment]
1.9.0 uses firewalld. What do your firewalld xml files look like?
