### ISSUE TITLE
SQL Server

### ISSUE THREAD

**Issue by wawelon** [DigitalRuby/IPBan#281]
how to configure ipban to block unsuccessful login attempts in sql server

**Comment by jjxtra** [comment]
It's already setup to do this.

**Comment by wawelon** [comment]
He did not block IP access until I personally added the IP address

**Comment by jjxtra** [comment]
If you have an event viewer for a failed login, please post it, otherwise this is a complete guessing game.

**Comment by AntiTenzor** [comment]
I have emulated failed login to Microsoft SQL Server when connecting over TCP with user/pass authentication.

There is a record in EventViewer for this situation.
Login failed for user 'fail'. Reason: Could not find a login matching the name provided. [**CLIENT: 127.0.0.1**]

It is located in "**Windows logs**" --> "**Application**" 'folder'.
EventID = **18456**
Source (aka Provider) = **MSSQLSERVER**

Here is XML of this event:

[-](https://github.com/DigitalRuby/IPBan/issues/281#)
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/DigitalRuby/IPBan/issues/281#)
<System>
  <Provider Name="MSSQLSERVER" /> 
  <EventID Qualifiers="49152">18456</EventID> 
  <Level>0</Level> 
  <Task>4</Task> 
  <Keywords>0x90000000000000</Keywords> 
  <TimeCreated SystemTime="2026-04-16T13:38:52.131943800Z" /> 
  <EventRecordID>19109251</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>SomeComputerName</Computer> 
  <Security /> 
  </System>
[-](https://github.com/DigitalRuby/IPBan/issues/281#)
<EventData>
  <Data>fail</Data> 
  <Data>Reason: Could not find a login matching the name provided.</Data> 
  <Data>[CLIENT: 127.0.0.1]</Data> 
  <Binary>184800000E00000008000000480045005A0044004100540041000000070000006D00610073007400650072000000</Binary> 
  </EventData>
  </Event>

**Comment by AntiTenzor** [comment]
<img width="1533" height="426" alt="Image" src="https://github.com/user-attachments/assets/7925d909-79d1-4235-b028-f109ae13408b" />
