### ISSUE TITLE
Failed MSSQL Logins being identified as RDP

### ISSUE THREAD

**Issue by gawainXX** [DigitalRuby/IPBan#286]
I'm currently working on an issue where failed logins to a MS SQL Server 2022 instance appear to be getting flagged as RDP traffic?
Example :
2024-01-04 09:11:30.5881|WARN|IPBan|Login failure: 71.36.112.202, , RDP, 2, 5152

Looking over the config file, I do notice that the default MSSQL rules appears to be looking for a source named "MSSQL" whereas the source in Windows Event Logs that I'm seeing associated with failed logins is "MSSQLSERVER"

I'm currently adjusting the config file to see if I can remediate this but would appreciate guidance.

**Comment by jjxtra** [comment]
Post event viewer xml

**Comment by gawainXX** [comment]
> Post event viewer xml

INVALID LOGIN:

Log Name:      Application
Source:        MSSQLSERVER
Date:          1/4/2024 8:06:58 AM
Event ID:      18456
Task Category: Logon
Level:         Information
Keywords:      Classic,Audit Failure
User:          N/A
Computer:      vmcissqldb01
Description:
Login failed for user 'vice'. Reason: Could not find a login matching the name provided. [CLIENT: 123.30.240.80]
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MSSQLSERVER" />
    <EventID Qualifiers="49152">18456</EventID>
    <Version>0</Version>
    <Level>0</Level>
    <Task>4</Task>
    <Opcode>0</Opcode>
    <Keywords>0x90000000000000</Keywords>
    <TimeCreated SystemTime="2024-01-04T16:06:58.9357365Z" />
    <EventRecordID>10899</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>vmcissqldb01</Computer>
    <Security />
  </System>
  <EventData>
    <Data>vice</Data>
    <Data> Reason: Could not find a login matching the name provided.</Data>
    <Data> [CLIENT: 123.30.240.80]</Data>
    <Binary>184800000E0000000D00000076006D00630069007300730071006C0064006200300031000000070000006D00610073007400650072000000</Binary>
  </EventData>
</Event>

FAILED LOGIN:
Log Name:      Application
Source:        MSSQLSERVER
Date:          1/4/2024 8:06:56 AM
Event ID:      18456
Task Category: Logon
Level:         Information
Keywords:      Classic,Audit Failure
User:          N/A
Computer:      vmcissqldb01
Description:
Login failed for user 'sa'. Reason: Password did not match that for the login provided. [CLIENT: 123.30.240.80]
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MSSQLSERVER" />
    <EventID Qualifiers="49152">18456</EventID>
    <Version>0</Version>
    <Level>0</Level>
    <Task>4</Task>
    <Opcode>0</Opcode>
    <Keywords>0x90000000000000</Keywords>
    <TimeCreated SystemTime="2024-01-04T16:06:56.1385376Z" />
    <EventRecordID>10897</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>vmcissqldb01</Computer>
    <Security />
  </System>
  <EventData>
    <Data>sa</Data>
    <Data> Reason: Password did not match that for the login provided.</Data>
    <Data> [CLIENT: 123.30.240.80]</Data>
    <Binary>184800000E0000000D00000076006D00630069007300730071006C0064006200300031000000070000006D00610073007400650072000000</Binary>
  </EventData>
</Event>

**Comment by jjxtra** [comment]
Raw xml

**Comment by gawainXX** [comment]
**Invalid Login**
Log Name:      Application
Source:        MSSQLSERVER
Date:          1/4/2024 8:06:58 AM
Event ID:      18456
Task Category: Logon
Level:         Information
Keywords:      Classic,Audit Failure
User:          N/A
Computer:      REDACTED
Description:
Login failed for user 'vice'. Reason: Could not find a login matching the name provided. [CLIENT: 123.30.240.80]
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MSSQLSERVER" />
    <EventID Qualifiers="49152">18456</EventID>
    <Version>0</Version>
    <Level>0</Level>
    <Task>4</Task>
    <Opcode>0</Opcode>
    <Keywords>0x90000000000000</Keywords>
    <TimeCreated SystemTime="2024-01-04T16:06:58.9357365Z" />
    <EventRecordID>10899</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>REDACTED</Computer>
    <Security />
  </System>
  <EventData>
    <Data>vice</Data>
    <Data> Reason: Could not find a login matching the name provided.</Data>
    <Data> [CLIENT: 123.30.240.80]</Data>
    <Binary>184800000E0000000D00000076006D00630069007300730071006C0064006200300031000000070000006D00610073007400650072000000</Binary>
  </EventData>
</Event>

**Failed Login**
Log Name:      Application
Source:        MSSQLSERVER
Date:          1/4/2024 8:06:57 AM
Event ID:      18456
Task Category: Logon
Level:         Information
Keywords:      Classic,Audit Failure
User:          N/A
Computer:      REDACTED
Description:
Login failed for user 'sa'. Reason: Password did not match that for the login provided. [CLIENT: 123.30.240.80]
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MSSQLSERVER" />
    <EventID Qualifiers="49152">18456</EventID>
    <Version>0</Version>
    <Level>0</Level>
    <Task>4</Task>
    <Opcode>0</Opcode>
    <Keywords>0x90000000000000</Keywords>
    <TimeCreated SystemTime="2024-01-04T16:06:57.5294251Z" />
    <EventRecordID>10898</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>REDACTED</Computer>
    <Security />
  </System>
  <EventData>
    <Data>sa</Data>
    <Data> Reason: Password did not match that for the login provided.</Data>
    <Data> [CLIENT: 123.30.240.80]</Data>
    <Binary>184800000E0000000D00000076006D00630069007300730071006C0064006200300031000000070000006D00610073007400650072000000</Binary>
  </EventData>
</Event>

**Comment by gawainXX** [comment]
Failed Login
`
Log Name:      Application
Source:        MSSQLSERVER
Date:          1/4/2024 8:06:57 AM
Event ID:      18456
Task Category: Logon
Level:         Information
Keywords:      Classic,Audit Failure
User:          N/A
Computer:      REDACTED
Description:
Login failed for user 'sa'. Reason: Password did not match that for the login provided. [CLIENT: 123.30.240.80]
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MSSQLSERVER" />
    <EventID Qualifiers="49152">18456</EventID>
    <Version>0</Version>
    <Level>0</Level>
    <Task>4</Task>
    <Opcode>0</Opcode>
    <Keywords>0x90000000000000</Keywords>
    <TimeCreated SystemTime="2024-01-04T16:06:57.5294251Z" />
    <EventRecordID>10898</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>REDACTED</Computer>
    <Security />
  </System>
  <EventData>
    <Data>sa</Data>
    <Data> Reason: Password did not match that for the login provided.</Data>
    <Data> [CLIENT: 123.30.240.80]</Data>
    <Binary>184800000E0000000D00000076006D00630069007300730071006C0064006200300031000000070000006D00610073007400650072000000</Binary>
  </EventData>
</Event>
`
**Invalid Login**
`
Log Name:      Application
Source:        MSSQLSERVER
Date:          1/4/2024 8:06:58 AM
Event ID:      18456
Task Category: Logon
Level:         Information
Keywords:      Classic,Audit Failure
User:          N/A
Computer:      REDACTED
Description:
Login failed for user 'vice'. Reason: Could not find a login matching the name provided. [CLIENT: 123.30.240.80]
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MSSQLSERVER" />
    <EventID Qualifiers="49152">18456</EventID>
    <Version>0</Version>
    <Level>0</Level>
    <Task>4</Task>
    <Opcode>0</Opcode>
    <Keywords>0x90000000000000</Keywords>
    <TimeCreated SystemTime="2024-01-04T16:06:58.9357365Z" />
    <EventRecordID>10899</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>REDACTED</Computer>
    <Security />
  </System>
  <EventData>
    <Data>vice</Data>
    <Data> Reason: Could not find a login matching the name provided.</Data>
    <Data> [CLIENT: 123.30.240.80]</Data>
    <Binary>184800000E0000000D00000076006D00630069007300730071006C0064006200300031000000070000006D00610073007400650072000000</Binary>
  </EventData>
</Event>
`

**Comment by gawainXX** [comment]
Sorry, took a few tries to get it to keep the formatting.

**Comment by jjxtra** [comment]
Have created a unit test and it was identified as MSSQL, not RDP.

**Comment by gawainXX** [comment]
Hmmm, I'm currently using IPBAN 1.9.0.0 running on Windows Server 2022 (Desktop Experience)
Based on the logs, it appears to be identifying the traffic as "RDP" as well as not reporting the account?

My ipban.config is stock with the exception I've adjusted  the number of failed attempts and ban timer.

2024-01-04 20:02:40.3420|DEBUG|IPBan|Event viewer found: 92.94.91.95, MSSQL, vice, FailedLogin
2024-01-04 20:02:40.4400|WARN|IPBan|Login failure: 92.94.91.95, vice, MSSQL, 1, 18456

I do notice that it appears to be looking for a Source named "MSSQL" rather then MSSQLServer ?
`      <Group>
        <Source>MSSQL</Source>
        <Keywords>0x90000000000000</Keywords>
        <Path>Application</Path>
        <FailedLoginThreshold>0</FailedLoginThreshold>
        <Expressions>
          <Expression>
            <XPath>//Provider[contains(@Name,'MSSQL')]</XPath>
`

**Comment by gawainXX** [comment]
Upon further review, It looks like the SQL logins are being properly logged, 
I just need to puzzle out what's generating the supposed RDP attempts captured in the logs as 3389 is NOT exposed to the internet.

2024-01-04 08:07:09.7179|WARN|IPBan|IP 123.30.240.80, mssql, MSSQL ban pending.
2024-01-04 08:07:09.7194|WARN|IPBan|Updating firewall with 1 entries...

**Comment by gawainXX** [comment]
Ok, it looks like some of the failed SQL authentication attempts are getting caught by windows packet filtering (5152|4625) event IDs and classified as RDP as a result?
(We unfortunately do not have a choice whether this server is exposed to the internet, but it doesn't contain and CUI or PII)

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-a5ba-3e3b0328c30d}" /> 
  <EventID>5152</EventID> 
  <Version>1</Version> 
  <Level>0</Level> 
  <Task>12809</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8010000000000000</Keywords> 
  <TimeCreated SystemTime="2024-01-04T21:41:17.3952246Z" /> 
  <EventRecordID>10191988</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="4" ThreadID="10384" /> 
  <Channel>Security</Channel> 
  <Computer>REDACTED</Computer> 
  <Security /> 
  </System>
+ <EventData>
  <Data Name="ProcessId">0</Data> 
  <Data Name="Application">-</Data> 
  <Data Name="Direction">%%14592</Data> 
  <Data Name="SourceAddress">71.36.112.202</Data> 
  <Data Name="SourcePort">65376</Data> 
  <Data Name="DestAddress">192.168.134.15</Data> 
  <Data Name="DestPort">1433</Data> 
  <Data Name="Protocol">6</Data> 
  <Data Name="FilterOrigin">Stealth</Data> 
  <Data Name="FilterRTID">73435</Data> 
  <Data Name="LayerName">%%14597</Data> 
  <Data Name="LayerRTID">13</Data> 
  </EventData>
  </Event>
```

**Comment by jjxtra** [comment]
Not sure how to resolve this other than removing the packet filtering event viewer rule. But that might leave your real RDP vulnerable.

**Comment by gawainXX** [comment]
> Not sure how to resolve this other than removing the packet filtering event viewer rule. But that might leave your real RDP vulnerable.

Hmm, in the case of the event I had referenced, is that likely due to a host continuing to try to authenticate against SQL, after IPBAN has blocked it's IP? Generating a traffic filter event due to the dropped packet?

Those (RDP) messages are flooding the MSSQL events out of the logs though. Is there perhaps an easy way I can direct application specific messages to their own discrete log file so that the block actions aren't drowned out?
Alternatively, is there a way via ipban.override.config to disable the RDP monitor, or would I need to remove all related sections from ipban.config ?

**Comment by jjxtra** [comment]
Turn off drop packet logging.

https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-filtering-platform-packet-drop

**Comment by gawainXX** [comment]
> Turn off drop packet logging.
> 
> https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-filtering-platform-packet-drop

Thank you, i dug a bit deeper and found that the majority of these were actually false alerts from windows SSDP Discovery,

Could you possibly assist me in updating the RDP Source rule to exclude packets on dest port 1900, ideally via the overrides config file?

Here's one such event;
```
Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          1/7/2024 3:56:14 AM
Event ID:      5152
Task Category: Filtering Platform Packet Drop
Level:         Information
Keywords:      Audit Failure
User:          N/A
Computer:      REDACTED
Description:
The Windows Filtering Platform has blocked a packet.

Application Information:
	Process ID:		0
	Application Name:	-

Network Information:
	Direction:		Inbound
	Source Address:		192.168.134.80
	Source Port:		53182
	Destination Address:	239.255.255.250
	Destination Port:		1900
	Protocol:		17

Filter Information:
	Filter Origin:		Stealth
	Filter Run-Time ID:	73435
	Layer Name:		Transport
	Layer Run-Time ID:	13
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-a5ba-3e3b0328c30d}" />
    <EventID>5152</EventID>
    <Version>1</Version>
    <Level>0</Level>
    <Task>12809</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8010000000000000</Keywords>
    <TimeCreated SystemTime="2024-01-07T11:56:14.0247656Z" />
    <EventRecordID>10568273</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="12360" />
    <Channel>Security</Channel>
    <Computer>REDACTED</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="ProcessId">0</Data>
    <Data Name="Application">-</Data>
    <Data Name="Direction">%%14592</Data>
    <Data Name="SourceAddress">192.168.134.80</Data>
    <Data Name="SourcePort">53182</Data>
    <Data Name="DestAddress">239.255.255.250</Data>
    <Data Name="DestPort">1900</Data>
    <Data Name="Protocol">17</Data>
    <Data Name="FilterOrigin">Stealth</Data>
    <Data Name="FilterRTID">73435</Data>
    <Data Name="LayerName">%%14597</Data>
    <Data Name="LayerRTID">13</Data>
  </EventData>
</Event>
```
Thank you in advance!

**Comment by jjxtra** [comment]
Add this to a group in the ExpressionsToBlock -> Groups element:

```xml
<Group>
  <Source>RDP</Source>
    <Keywords>0x8010000000000000</Keywords>
      <Path>Security</Path>

      <!-- Override failed login threshold or leave 0 for default -->
      <FailedLoginThreshold>0</FailedLoginThreshold>

      <!-- Optional, set a log level, must match exactly (case sensitive) one of the following:
        Trace, Debug, Info, Warn, Error, Critical
      <LogLevel>Warn</LogLevel>		
      -->		
	<Expressions>
	  <Expression>
		<XPath>//EventID</XPath>
		<Regex>
			<![CDATA[
				^(?<log>4625|5152|6273)$
			]]>
		</Regex>
	  </Expression>
	  <Expression>
		<XPath>//Data[@Name='IpAddress' or @Name='Workstation' or @Name='SourceAddress' or @Name='ClientIPAddress']</XPath>
		<Regex>
		  <![CDATA[
			(?<ipaddress>.+)
		  ]]>
		</Regex>
	  </Expression>
	  <Expression>
		<XPath>//Data[@Name='ProcessName']</XPath>
		<Regex>
		  <![CDATA[
			(?<source_IIS>c:\\Windows\\System32\\inetsrv\\w3wp.exe)?$
		  ]]>
		</Regex>
	  </Expression>
	  <Expression>
	    <XPath>//Data[@Name='DestPort'</XPath>
		<Regex>
		  <![CDATA[
			^(?!1900$).*
		  ]]>		
		</Regex>
	  </Expression>
	</Expressions>
</Group>
```
