### ISSUE TITLE
Add riscv64 support

### ISSUE THREAD

**Issue by liberodark** [DigitalRuby/IPBan#288]
Hi,

Please can you add riscv64 support on your release ?
Also have riscv64 servers if you want to work on it ?

Best Regards

**Comment by jjxtra** [comment]
If you can provide some log file snippets or event viewer xml, possibly.

**Comment by liberodark** [comment]
Yes i can give you full access on RISC-V Hardware for do that here : https://open-riscv-initiative.com

**Comment by jjxtra** [comment]
Need path to log files along with what a failed and successful login looks like. Please post here and I'd be happy to add a recipe.
