### ISSUE TITLE
Possible to turn off loggin when ban.txt/unban.txt files is used?

### ISSUE THREAD

**Issue by wazerstar** [DigitalRuby/IPBan#289]
Is it possible to turn logging of when importing bans via ban.txt and so when unbanning with unban.txt ?

ban expired would also be cool to be able to turn off.

This is no longer an option to do, I found this old ticket about reducing logging?

https://github.com/DigitalRuby/IPBan/issues/39

**Comment by wazerstar** [comment]
I found this, but is that not an error in the config file from release?

Should they both places be called FailedLoginLevel ? I would assume it would be called SuccessLoginLogLevel at the first one, assuming its a copy paste or type error?

**Comment by jjxtra** [comment]
What did you find exactly?

**Comment by wazerstar** [comment]
> What did you find exactly?

Nothing but that error written twice FailedLoginLevel, SuccessLoginLogLevel was missing in there correct?

Anyways is it possible to turn off logging for income of ban/unban ?

**Comment by jjxtra** [comment]
`SuccessfulLoginLogLevel` is an option.
