### ISSUE TITLE
Possible to add Caddy recipe support?

### ISSUE THREAD

**Issue by wazerstar** [DigitalRuby/IPBan#291]
https://caddyserver.com/

https://github.com/caddyserver/caddy

https://caddy.community/

**Comment by kimboslice99** [comment]
If you post some logs that show what a failed login looks like, I can make a config for ya

**Comment by jjxtra** [comment]
Please post here with a log file path and an example of what a failed and successful login look like, and I'll be happy to make a recipe.

**Comment by jjxtra** [comment]
@wazerstar Recipe here: https://github.com/DigitalRuby/IPBan/blob/master/Recipes/Windows/LogFile/Caddy.xml
