### ISSUE TITLE
Windows firewall rules

### ISSUE THREAD

**Issue by mycanaletto** [DigitalRuby/IPBan#293]
Hello,
I'm currently testing the Personal/Pro version.

There's one thing I don't understand, it never creates the rules in the firewall. For example, if I whitelist or blacklist an IP, this should happen?

I've tested it on two machines, with the same result (w2016/2019)

However, it does see my RDP connection in recent activity.

Another question: if I use Cloudflare's reverse proxy, should I whitelist Cloudflare IPs?

I did a .csv import, and then it adds them but overwrites the ip's already entered.

Thank you.

lionel

**Comment by jjxtra** [comment]
Pro version uses Windows Filtering Platform on Windows.

Run from admin powershell and search for ipban:

`netsh wfp show filters "file=c:/filters.xml"; notepad "c:/filters.xml"`
