### ISSUE TITLE
Ban entire /24 subnet range?

### ISSUE THREAD

**Issue by 29039** [DigitalRuby/IPBan#298]
I have noticed that consecutive IP addresses are getting banned. Thanks IPBan for doing your job! But just wondering if it is possible to slow them down even further by banning the whole range at once not just the particular IP. Is this already a feature? If not hope this would not be too hard.

**Comment by jjxtra** [comment]
I can look at adding an app setting for this

**Comment by Paprikar** [comment]
I think its possible regex-wise,
Just create ad-hoc group for blocking this (or mby more) specific ip range.

**Comment by jjxtra** [comment]
This is added as a feature of ipban pro in the 3.4.0 beta release.

**Comment by jjxtra** [comment]
https://github.com/DigitalRuby/IPBanProReleases/releases/tag/3.4.0
