### ISSUE TITLE
1.1.1.1 banned? Why?

### ISSUE THREAD

**Issue by salusalpha** [DigitalRuby/IPBan#304]
Jeff I do not understand why cloudflare DNS would do RDP and why it is blocked? How to handle? Thanks

2024-07-12 20:24:13.6183|WARN|IPBan|Login failure: 1.1.1.1, , RDP, 5, 5152
2024-07-12 20:24:13.6183|INFO|IPBan|IP blacklisted: False, user name blacklisted: False, user name edit distance blacklisted: False, user name whitelisted: False
2024-07-12 20:24:13.6183|WARN|IPBan|Banning ip address: 1.1.1.1, user name: , config blacklisted: False, count: 5, extra info: , duration: 1.00:00:00
2024-07-12 20:24:13.6183|WARN|IPBan|Updating firewall with 1 entries...
2024-07-12 20:24:13.6183|INFO|IPBan|Firewall entries updated: 1.1.1.1

**Comment by jjxtra** [comment]
If you can find this in the event viewer, we can track it down. My guess is it's a dropped packet causing the block.

**Comment by jjxtra** [comment]
```xml
<!-- This group will block audit failures from failed login attempts, along with dropped packets to Windows -->
<Group>
<Source>RDP</Source>
<Keywords>0x8010000000000000</Keywords>
<Path>Security</Path>

<!-- Override failed login threshold or leave 0 for default -->
<FailedLoginThreshold>0</FailedLoginThreshold>

<!-- Optional, override minimum time between login attempts
	<MinimumTimeBetweenLoginAttempts>00:00:00:01</MinimumTimeBetweenLoginAttempts>
-->

<!-- Optional, set a log level, must match exactly (case sensitive) one of the following:
	Trace, Debug, Info, Warn, Error, Critical
	<LogLevel>Warn</LogLevel>		
-->

<Expressions>
	<Expression>
		<XPath>//EventID</XPath>
		<Regex>
			<![CDATA[
				^(?<log>4625|5152|6273)$
			]]>
		</Regex>
	</Expression>
	<Expression>
		<XPath>//Data[@Name='IpAddress' or @Name='Workstation' or @Name='SourceAddress' or @Name='ClientIPAddress']</XPath>
		<Regex>
			<![CDATA[
				(?<ipaddress>.+)
			]]>
		</Regex>
	</Expression>
	<Expression>
		<XPath>//Data[@Name='ProcessName']</XPath>
		<Regex>
			<![CDATA[
				(?<source_IIS>c:\\Windows\\System32\\inetsrv\\w3wp.exe)?$
			]]>
		</Regex>
	</Expression>
</Expressions>
</Group>
```

**Comment by jjxtra** [comment]
```xml
<!-- This group will block audit failures from failed login attempts, along with dropped packets to Windows -->
<Group>
<Source>RDP</Source>
<Keywords>0x8010000000000000</Keywords>
<Path>Security</Path>

<!-- Override failed login threshold or leave 0 for default -->
<FailedLoginThreshold>0</FailedLoginThreshold>

<!-- Optional, override minimum time between login attempts
	<MinimumTimeBetweenLoginAttempts>00:00:00:01</MinimumTimeBetweenLoginAttempts>
-->

<!-- Optional, set a log level, must match exactly (case sensitive) one of the following:
	Trace, Debug, Info, Warn, Error, Critical
	<LogLevel>Warn</LogLevel>		
-->

<Expressions>
	<Expression>
		<XPath>//EventID</XPath>
		<Regex>
			<![CDATA[
				^(?<log>4625|5152|6273)$
			]]>
		</Regex>
	</Expression>
	<Expression>
		<XPath>//Data[@Name='IpAddress' or @Name='Workstation' or @Name='SourceAddress' or @Name='ClientIPAddress']</XPath>
		<Regex>
			<![CDATA[
				(?<ipaddress>.+)
			]]>
		</Regex>
	</Expression>
	<Expression>
		<XPath>//Data[@Name='ProcessName']</XPath>
		<Regex>
			<![CDATA[
				(?<source_IIS>c:\\Windows\\System32\\inetsrv\\w3wp.exe)?$
			]]>
		</Regex>
	</Expression>
</Expressions>
</Group>
```

**Comment by jjxtra** [comment]
You can disable dropped packet logging in group policy to confirm.

**Comment by jjxtra** [comment]
If cloudflare is your dns server, you should whitelist 1.1.1.1 and 1.0.0.1

**Comment by jaltman** [comment]
> Jeff I do not understand why cloudflare DNS would do RDP and why it is blocked? How to handle? Thanks
> 
> 2024-07-12 20:24:13.6183|WARN|IPBan|Login failure: 1.1.1.1, , RDP, 5, 5152 2024-07-12 20:24:13.6183|INFO|IPBan|IP blacklisted: False, user name blacklisted: False, user name edit distance blacklisted: False, user name whitelisted: False 2024-07-12 20:24:13.6183|WARN|IPBan|Banning ip address: 1.1.1.1, user name: , config blacklisted: False, count: 5, extra info: , duration: 1.00:00:00 2024-07-12 20:24:13.6183|WARN|IPBan|Updating firewall with 1 entries... 2024-07-12 20:24:13.6183|INFO|IPBan|Firewall entries updated: 1.1.1.1

@salusalpha, one likely scenario is that an attacker is sending UDP packets to the RDP port on your server using a spoofed address in an attempt to trigger the sending of an amplified response to the spoofed address.   In other words, you server is being used as part of a DRDoS attack against cloudfare.

**Comment by salusalpha** [comment]
> If cloudflare is your dns server, you should whitelist 1.1.1.1 and 1.0.0.1

hi jeff.....

like you indicated i can not get the record in event viewer with 1.1.1.1. I checked for events IDs  4625 5152 6273

I also added 1.1.1.1. to whitelist 

<add key="Whitelist" value="
		1.1.1.1
		"/>
		
it did not help.     I have this issue basically on all machines where I set 1.1.1.1 DNS    ....... this is my I stopped using IPBan for a while.  I can only propose set on your NIC please DNS 1.1.1.1 and put your code under debugger maybe?

sorry for the inconvenience

hope to be a user again.

**Comment by jjxtra** [comment]
Send an export of your event viewer to support@ipban.com

**Comment by jjxtra** [comment]
You can remove `|5152` from your ipban.config to ignore these events.
