### ISSUE TITLE
*IMPORTANT* Phishing Warning

### ISSUE THREAD

**Issue by jjxtra** [DigitalRuby/IPBan#313]
Test to verify phishing attack

**Comment by jjxtra** [comment]
Phishing attack confirmed. Email originally read:

Hey there!

We have detected a security vulnerability in your repository. Please contact us at link edited to avoid clicking: https github-scanner dot com to get more information on how to fix this issue.

Best regards,
Github Security Team

Anyone else gettign similar emails, be advised to ignore all links, as the bad actors use them to ask for your data.

**Comment by jaltman** [comment]
dozens of repos have been spammed

**Comment by da99Beast** [comment]
domain was setup today so yup
