### ISSUE TITLE
IPBan does not see the Windows 10 OpenSSH logfile

### ISSUE THREAD

**Issue by fejjj** [DigitalRuby/IPBan#317]
I'm using OpenSSH on Windows 10 and IPBan does not see the logfile.  If I add the log path to SSH \<PathAndMask> towards the top of the ipban.config, it doesn't get picked up by IPban.

As a workaround I've added the recipe from this discussion:
https://github.com/DigitalRuby/IPBan/discussions/283

So sorry if I've done something wrong!

**Comment by jjxtra** [comment]
OpenSSH should be writing to the event viewer and be picked up by the default config.
- Is OpenSSH not writing to the event viewer?
- If OpenSSH is writing to the event viewer, is ipban not picking up the failed logins from there?

**Comment by fejjj** [comment]
I had unknowingly disabled event viewer logging while troubleshooting a different issue, and was only logging to sshd.log.  Changing SysLogFacility from LOCAL0 back to AUTH in my sshd_config seems to have me fixed up.

Thank you for the fast response!
