### ISSUE TITLE
Firewall rule is deleted

### ISSUE THREAD

**Issue by imangm** [DigitalRuby/IPBan#44]
Hello Jeff,

Thank you for making IPBan. I've just installed it for the first time on a server 2 weeks ago. Yesterday I was checking the logs and I noticed that IPBan is not blocking brute-forces anymore. 

Just checked the firewall and there was no IPBan rules there too. I've checked firewall logs and found this:

```
A rule has been deleted in the Windows Firewall exception list.

Deleted rule: 
   Rule ID: xxx
   Rule Name: IPBan_0
   Modifying User: SYSTEM
   Modifying Application: D:\test\IPBan.exe
```

I've stopped and restarted IPBan service but it didn't help and IPBan rules didn't appear in firewall. I've also added an IP in blacklist (In config file) but it's not blocking anyway...

So, I've 2 questions:

1. Is it possible that IPBan delete its rule by itself or is it a hack attack which has removed this rule?
2. Is there any need that I recreate the firewall rule by my own or will it be created automatically by IPBan again?

Thank you again
Iman

**Comment by jjxtra** [comment]
It should auto-create. What version are you using?

**Comment by jjxtra** [comment]
Vesion 1.3.5 should be the fixed version, let me know what vesion you are using.

**Comment by jjxtra** [comment]
If you could check your event viewer and log file as well and email / post those that would be helpful too.

**Comment by jjxtra** [comment]
Please re-open the issue if you see this problem with v1.3.5.
