### ISSUE TITLE
Total Newbie needs help with Install

### ISSUE THREAD

**Issue by mteq** [DigitalRuby/IPBan#45]
Hi There
I have had someone trying to Hack into my server for a few months now, initially it was 25 Logins a second. I rebooted My DSL router and got a new IP Address and they went away for 24 Hours. I was using a Custom RDP port (15676 instead of The standard 3389) but they found me again ☹. I use a DynDns host name as fixed IP addresses are very expensive here And I figured a dynamic one would be safer. Now the Login attempts are much lower going back to port 3389 and limiting the IP Range to local addresses but they keep trying. They haven’t got in as my Password is tight but I stumbled across your IPBAN program by accident yesterday and I thought “I must try this”, I have been looking for something like This for ever. I am however a total Newbie though. I followed Instructions and downloaded the IPBAN app onto my Server 2012 R2 and followed these 
instructions:

Windows
•	For Windows, IPBan is supported on Windows Server 2008 or equivalent or newer. Windows XP and Server 2003 are NOT supported.
•	Extract the IPBan.zip (inside is IPBanWindows.zip) file to a place on your computer. Right click on all the extracted files and select properties. Make sure to select "unblock" if the option is available.
•	You MUST make this change to the local security policy to ensure ip addresses show up: Change Local Security Policy -> Local Policies -> Audit Policy and turn failure logging on for "audit account logon events" and "audit logon events". From an admin command prompt:
auditpol /set /category:"Logon/Logoff" /success:enable /failure:enable
auditpol /set /category:"Account Logon" /success:enable /failure:enable

However when I downloaded Visual Studio 2017 Free, it seems like you have to Compile the program? (Apologies if My wording is wrong) I ran IPBAN service and that shows running, I can get IPBAN to launch with a CMD window But from then on I am stuck. I see all the Clever IT guys don’t have a problem. Is there a tutorial somewhere on how To make the GUI work and compile the program in Visual Studio 2017 or am I totally on the wrong track?

I really love supporting open source software developers because they make really great software and although I am only a small struggling one man business I donate as much as I can. I see you will be going commercial soon? Will the Open Source version still work? Do you have any idea on pricing?

I will gladly donate if IPBAN does what it seems everyone on GitHub suggests.

Thanks in anticipation to any helpers

**Comment by jjxtra** [comment]
Just download the release from the github releases page (click code and then click releases), extract to a folder and setup as a Windows service. No need for Visual Studio unless you are making changes to the source code.

The commercial version will do a lot more and I haven't figured out pricing for that yet.

**Comment by mteq** [comment]
Thanks Jeff

 

Sorry to bother you, I will try figure it out

 

Regards

 

Dean aka Dan Brown (Don’t ask)
