### ISSUE TITLE
questions around logging/config with windows installations..

### ISSUE THREAD

**Issue by ljwobker** [DigitalRuby/IPBan#47]
I'm trying to get my head around how the logging (For Windows) is set up / configured for IPBan.  I've looked through the nLog docs briefly and I think I understand their basic structure... but for IPBan, at least in a "default" windows install, there appears to be no nlog.config or nlog.dll.config file included in that zipfile distribution.  

Is this intentional?  I see the nlog.config file in the root of the repo, but the mapping between the repo file locations and the distribution files is not obvious (yet?)....  Is the expectation that users will copy-possibly-modify the nlog.config file from the base repo and put that in the same directory with the rest of the windows installation?  Or is there another way to configure nLog from within a windows install that I haven't found yet?  If I can get this figured out I'm happy to do another PR with some additions to the readme file  ;-)

**Comment by jjxtra** [comment]
NLog is built in, you don't need an nlog.config file. If you want to customize the logging, you can drop the nlog.config file into the folder and it will override the defaults, which are hard-coded in the ipban executable.
