### ISSUE TITLE
IPBan rule in windows firewall is missing

### ISSUE THREAD

**Issue by marcwaz** [DigitalRuby/IPBan#48]
I have just downloaded the latest version (1.3.5) and put into place on an up-to-date Windows 2012 R2 Standard Edition server. I have noticed that the IPBan rule in the advanced windows firewall is not automatically created, while I have launched the IPBan program (as an executable or windows service, the result is the same).
Any idea ?
I confirm that the clear ban option on start is set to false in the config file.

**Comment by jjxtra** [comment]
Also running on the same OS without issue. Rule will not show up until first ban. Do you see any bans in your log file?

**Comment by marcwaz** [comment]
You are right, after the first ban, the rule has appeared. thx!
