### ISSUE TITLE
Firewall rule being deleted

### ISSUE THREAD

**Issue by Lasse-B** [DigitalRuby/IPBan#51]
Hey there,

thank you very much for writing and maintaining this jewel of a tool.

Unfortunately I seem to have hit a roadblock with it. Same issue as the guy in #44 apparently. The firewall rule is deleted just a fraction of a second after it was created.

XML of rule creation:
https://pastebin.com/FTcTREEi

XML of rule deletion:
https://pastebin.com/iRFD2SrB

&nbsp;

&nbsp;

Additional info:

IPBan version is 1.3.6

ClearBannedIPAddressesOnRestart is set to false

Some tools rely on internal Windows functions and how / in what language these functions return results. Knowing that, I first tested IPBan on a US Win Server 2016 Standard Desktop that I had available at that time, where everything was just fine. Later, as our customer is a German company, I tried running IPBan on a German Win Server 2016 Standard Desktop. It is this German version of the server where the rule is deleted. The language used might have something to do with it, it might not, but it's where both systems differ. The XML output above is from said German Win Server 2016 standard install.

**Comment by jjxtra** [comment]
On Windows, setting the ip address list to an empty string actually turns it into a * which is quite odd, so as a fallback after the rule is created, I then immediately delete it if the ip address string was empty, to avoid a rule that blocks all traffic.

I will change the logic to just delete the rule if it exists if the ip string is empty, and not bother creating it.

Either way I think you are OK in this scenario. Are you able to see ip addresses getting blocked if you remote in from a test machine?

**Comment by Lasse-B** [comment]
> Are you able to see ip addresses getting blocked if you remote in from a test machine with failed logins?

No, that's what I tried initially and what generated the block rule together with its immediate deletion. However, both the IPv4 and IPv6 addresses from which the failed login attempts originate show up in the IPBan log file just fine:

> 2019-01-16 21:39:17.7067|WARN|IPBan.IPBanLog|Banning ip address: fe80::c872:be03:5c94:4af2%2, user name: administrator, config black listed: False, count: 5, extra info: 
2019-01-16 21:39:17.7744|WARN|IPBan.IPBanLog|Banning ip address: 192.168.0.20, user name: administrator, config black listed: False, count: 5, extra info:

**Comment by jjxtra** [comment]
The best suggestion I can give now is to increase the nlog.config levels to Debug or Diagnostic and see if we learn anything helpful

**Comment by jjxtra** [comment]
Also can you post the IPBan.dll.config file?

**Comment by jjxtra** [comment]
Do you see any "Un-banning ip address" in the log file?

**Comment by jjxtra** [comment]
Can you post the log file with the problem and in Debug level?

**Comment by Lasse-B** [comment]
> The other issue was when the max count overflowed, that bug has been fixed. Is this a new install or has it been running for a while?

It's a fresh install, completely patched

New data:
Just as I was failing logins on purpose to generate entries for the log file, IPBan banned me successfully. Here's the log file with levels set to debug.
https://pastebin.com/ii9rkw1f

internalLogLevel="Debug" doesn't seem to generate more or different entries.

What's different to yesterday evening is this:
Yesterday evening when IPBan was deleting the firewall rule just after its creation, I was attempting to access my test server from within the same LAN and IP subnet where the server is. Today I'm at work again so I have to VPN into the LAN where the test server is. This gives me an IP address of the VPN connection and not one of the same subnet as the one the server has. Maybe server and client residing in the same subnet is what's causing this?

**Comment by jjxtra** [comment]
So it is working as long as you are not on the same LAN as the server?

**Comment by jjxtra** [comment]
Trace is the log level you want for max information

**Comment by Lasse-B** [comment]
> So it is working as long as you are not on the same LAN as the server?

Exactly.

Here's the debug log; I did however edit out my public IP address:
https://www39.zippyshare.com/v/50zik9hs/file.html

It's rather large, 300kbyte-ish, so I zipped it and uploaded it to a file hoster. The first ban is logged at line 500.

**Comment by jjxtra** [comment]
Can you email it to support@digitalruby.com?

**Comment by jjxtra** [comment]
Nothing is obvious from the log file, other than it seems to pick up an ipv6 and then ipv4 address. Does this problem happen if you disable ipv6 on the client?

**Comment by Lasse-B** [comment]
Eureka! Disabling IPv6 on the client worked.

**Comment by jjxtra** [comment]
What about disabling ipv4?

**Comment by Lasse-B** [comment]
Sorry it took so long, had to set up a working IPv6 configuration first.

IPBan recognizes the IPv6 address, but doesn't make any entries into the firewall. Logfile (in debug mode) doesn't show anything out of the ordinary.

Btw, is there a way to capture every failed login? I've set MinimumTimeBetweenFailedLoginAttempts to 00:00:00:00 but it still seems to capture failed logins at a rate of one attempt per second.

**Comment by jjxtra** [comment]
If you increase the log level to 'Info' do you see all the failed logins in the logfile.txt file?

I'll do some ipv6 testing, clearly it is not handling ipv6 well.

**Comment by Lasse-B** [comment]
Here's an example from last night, two different IP addresses that just happened to happen in sequence:
`2019-01-23 02:50:35.5614|WARN|IPBan.IPBanLog|Login attempt failed: x.x.252.216, , RDP, 1
2019-01-23 02:50:50.5833|WARN|IPBan.IPBanLog|Login attempt failed: x.x.252.216, adminisstrator, RDP, 2
2019-01-23 02:50:50.5833|WARN|IPBan.IPBanLog|Banning ip address: x.x.252.216, user name: , config black listed: False, count: 5, extra info: 
2019-01-23 02:54:50.8464|WARN|IPBan.IPBanLog|Login attempt failed: x.x.224.177, administrator, RDP, 3
2019-01-23 02:55:05.8606|WARN|IPBan.IPBanLog|Banning ip address: x.x.224.177, user name: administrator, config black listed: False, count: 10, extra info: `
Counter for the first IP went 1, 2, 5 = ban
Counter for the second IP went 3, 10 = ban

This is with the config set like this:
`<add key="MinimumTimeBetweenFailedLoginAttempts" value="00:00:00:00"/>`



nlog.config is set as so:
` <logger name="*" minlevel="Info" writeTo="logfile"/>`

I'm now running IPBan on our customer's machine and it's doing a great job so far. It's just this one kink that would be awesome if it could be worked out / fixed / explained.

BTW, just for my understanding: how does DNS name in the whitelist work? Does IPBan do an nslookup for every IP checking if it resolves to the domain name as specified in the whitelist?

Anyway, you definitely got yourself a good crate of beer incoming when I get home tonight. It's well deserved!

**Comment by jjxtra** [comment]
I will investigate more on this, I think there is a subtle bug.

If you enter a host name instead of an ip as one of the whitelist or blacklist entries, it will query for all the ip addresses for that host name and insert them. An easy way to use your local host name for your data center in order to ensure that internal machines are auto whitelisted.

**Comment by jjxtra** [comment]
I can confirm that ipv6 addresses with the percent are causing the problem, I will look at stripping the % off and upload a new version once I have a fix.

**Comment by jjxtra** [comment]
Please try the latest release, 1.4.0 and let me know if it helps. I think it will work. Reopen the issue if it does not.
