### ISSUE TITLE
Set "Network Security: LAN Manager authentication level" for NTLMv2

### ISSUE THREAD

**Issue by mganss** [DigitalRuby/IPBan#56]
I found that I also had to set "Network Security: LAN Manager authentication level" to "Send NTLMv2 response only. Refuse LM & NTLM". The initial setting was "Not Defined" and I could no longer connect through RDP after setting "Network Security: Restrict NTLM: Incoming NTLM traffic" to "Deny all accounts". This is on Windows Server 2008 R2.

**Comment by jjxtra** [comment]
Yes there is no other option on Server 2008 R2 unfortunately. I will update the readme to be more clear.
