### ISSUE TITLE
Starting app looks for "Users/Jeff" (Windows)

### ISSUE THREAD

**Issue by chefbennyj1** [DigitalRuby/IPBan#57]
HI Jeff, when I start the app, it errors in the console and says it can't create event viewer because, I'm pretty sure, it is looking for "C:/Users/**Jeff**\Documents" folder.

Any way the CS is erroring on line 194 of IPBanWindowsEventViewer class.

for me anyway.

**Comment by jjxtra** [comment]
Can you post the full error? It is probably giving a reference to source file paths in an exception.

**Comment by jjxtra** [comment]
Ugh looks like visual studio falls to pieces if the generate nuget package option is on and you do a dotnet publish command. Try again in a bit and re-download, new version will be 1.4.4.

**Comment by jjxtra** [comment]
Please note that the new executable is 'DigitalRuby.IPBan.exe' which is different than just 'IPBan.exe' which is what it has been for the last 7 years.

**Comment by chefbennyj1** [comment]
Thank you. This is exactly the application I've been looking for to use with windows.
Thank you for creating this sir!
