### ISSUE TITLE
Clarify documentation on why disable NLA

### ISSUE THREAD

**Issue by ElimAdmin** [DigitalRuby/IPBan#58]
Hello Jeff. Thank you for making your work on this available.  I implemented this on one of our servers.  It was working, I then disconnected, now cannot regain RDP access.  I have setup a new Windows 2016 server, and want to make sure I have the settings right this time.

1. Re instruction "For Windows Server 2008 or equivalent, you should disable NTLM logins and only allow NTLM2 logins. On Windows Server 2008, there is no way to get the ip address of NTLM logins. Use secpol -> local policies -> security options -> network security restrict ntlm incoming ntlm traffic -> deny all accounts."

Does this also apply to Windows Server 2016?  

2. If there are more than 5 previous audit fail entries in the existing event log FOR MY IP address - will I be automatically banned?  I.e. does IPBan ban IPs based on historical events in the audit log, or only on events 'from here on'?  

3. Re: "On some Windows versions, NLA will default to on. This will lock you out of remote desktop, so make sure to turn this option off."  Can you please expand or explain this in your instructions.  You could add "When NLA (network level authentication) is turned on the IP addresses of the clients trying to log in is not stored in the security audit logs.  This makes it  harder to block brute force or dictionary attacks by a means of a firewall. Having NLA turned on will lock your out because..."    

I did not make this change (overlooked it), so I presume this is what locked me out.

Thank you.
Ken

**Comment by jjxtra** [comment]
Likely it’s nla being on. I’ve locked myself out several times with it.

**Comment by jjxtra** [comment]
I updated the readme to denote when to turn off NLA.
