### ISSUE TITLE
IPBan Pro Beta, Initial Service

### ISSUE THREAD

**Issue by JzJad** [DigitalRuby/IPBan#63]
The initial service created by the IPBan Pro Beta package sets the Exec pointed to a .dll instead of the DigitalRuby.IPBanProDatacenter file. Just a heads up, figured this would be the best place to bring this up.
Linux
Ubuntu 18.04

**Comment by jjxtra** [comment]
Good catch! I'll need to do better testing on Linux. I will upload 0.1.3.0 by tomorrow to fix it. Look for it in the next day or so.
