### ISSUE TITLE
Version 1.4.7 ~ 8 - Windows x64?

### ISSUE THREAD

**Issue by thytetgc** [DigitalRuby/IPBan#64]
I want to update my current version, but not only found Windows x86 in the Downloads files.

**Comment by jjxtra** [comment]
There should be Linux-x64, win-x86, and win-x64 in the 1.5.0.0 download,
are you not seeing that?

**Comment by thytetgc** [comment]
x64 only exists in version 1.5.0

I would like to test version 1.4.7 and 1.4.8 first.

**Comment by jjxtra** [comment]
I don't have plans to back-build those with x64
