### ISSUE TITLE
Single release package

### ISSUE THREAD

**Issue by Indigo744** [DigitalRuby/IPBan#68]
Hello Jeff,

At this time of writing, there is only one release package that we can download: a single ZIP containing the binaries compiled for Linux, Win32 and Win64 (and maybe Mac in the future?).

It is somewhat a pity to need to download all 3 binaries just for using a single one. When I know I'm on Windows x64, Linux and Win32 don't interest me, and thus consume bandwidth for nothing.

It would be so much simpler if instead of a single ZIP, the three different ZIP would be downloadable directly.

I don't know if that fits your delivery process. I'd love to hear your though about it.

Thanks a lot 😸

**Comment by jjxtra** [comment]
I will adjust the build script to produce a separate zip for each platform for next release.

**Comment by Indigo744** [comment]
Thanks, you're the best 😉

**Comment by jjxtra** [comment]
I went ahead and updated the current release to follow this pattern

**Comment by Indigo744** [comment]
This is really nice of you, thanks a lot!
