### ISSUE TITLE
Question: chocolatey installation

### ISSUE THREAD

**Issue by generik0** [DigitalRuby/IPBan#73]
Hi
This is very cool IPBAn. Great.
Any chance of a choco installer? 

Also your IPBan pro is not working. Would like to contribute, by buying IPBan Pro.

**Comment by jjxtra** [comment]
What is chco? I’m going to need more details about your issue with IPBan pro...

**Comment by generik0** [comment]
My bad. https://chocolatey.org/.. I.e. **choco**, not chco

**Comment by generik0** [comment]
IPBan Pro:

![image](https://user-images.githubusercontent.com/2411563/69875346-32e1d000-12bd-11ea-93e8-0e65ae6ab9ea.png)

**Comment by jjxtra** [comment]
I will look into it.

**Comment by jjxtra** [comment]
Chocolatey ended up being too complicated, so I made a one click install script that can be run from an admin powershell.

More details here: https://www.digitalruby.com/ipban-one-click-install-for-windows/

**Comment by 29039** [comment]
Shame the choco installer was too hard, but 1 click is a step in the right direction, maybe someone else will fill in the gap
