### ISSUE TITLE
Whitelist RegEx not working

### ISSUE THREAD

**Issue by beeeeswax** [DigitalRuby/IPBan#74]
I don't think I've overlooked anything but I've added a very simple regex to whitelist my local LAN's IP range but if I perform a couple of deliberately incorrect logins, the IPs are still being banned.

`<add key="WhitelistRegex" value="^(192\.168\.0\.*)"/>`

But then:

> Banning ip address: 192.168.0.172, user name: Admin, config black listed: True, count: 2, extra info: 

The RegEx checks out on regex101 so I think it's correct.  I do make use of the [UserNameWhitelist] option, does the IP whitelist not override this?  Any help appreciated.

**Comment by jjxtra** [comment]
I’ll make a unit test and get back

**Comment by garyfisher** [comment]
I confirm not working.

Regex test - 1: ^10\.0\.([0-1])\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))$
Regex test - 2: ^(10\.0\.0\.*)|(99\.99\.99\.[0-9])$

Version: IPBan 1.5.2.0
Windows 2012 R2 64 bit

**Comment by jjxtra** [comment]
I've fixed for 1.5.3.0, it has proper tests now.

**Comment by beeeeswax** [comment]
Thanks!  Is there any way to fudge this fix into 1,5,2.0 while we wait for a new release?  I've had to disable IPBan on both my home servers as it's currently doing silly things like banning the default gateway/router.

**Comment by jjxtra** [comment]
Release 1.5.3.0 version which has this one change and fixes the whitelist regex.
