### ISSUE TITLE
RRAS Support

### ISSUE THREAD

**Issue by jjxtra** [DigitalRuby/IPBan#76]
Add these RRAS event viewer to config file:

Failed login:

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="RemoteAccess" />
  <EventID Qualifiers="0">20271</EventID>
  <Level>3</Level>
  <Task>0</Task>
  <Keywords>0x80000000000000</Keywords>
  <TimeCreated SystemTime="2019-12-12T14:48:31.000000000Z" />
  <EventRecordID>1199774</EventRecordID>
  <Channel>System</Channel>
  <Computer>L1SDC02.l1s.loop1.com</Computer>
  <Security />
  </System>
- <EventData>
  <Data>{NA}</Data>
  <Data>user</Data>
  <Data>92.63.194.81</Data>
  <Data>The remote connection was denied because the user name and password combination you provided is not recognized, or the selected authentication protocol is not permitted on the remote access server.</Data>
  <Data>0x10</Data>
  <Binary>B3020000</Binary>
  </EventData>
  </Event>
```

Successful login:

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-A5BA-3E3B0328C30D}" />
  <EventID>6272</EventID>
  <Version>1</Version>
  <Level>0</Level>
  <Task>12552</Task>
  <Opcode>0</Opcode>
  <Keywords>0x8020000000000000</Keywords>
  <TimeCreated SystemTime="2019-12-13T19:48:39.420098200Z" />
  <EventRecordID>276341076</EventRecordID>
  <Correlation />
  <Execution ProcessID="616" ThreadID="3956" />
  <Channel>Security</Channel>
  <Computer>L1SDC02.l1s.loop1.com</Computer>
  <Security />
  </System>
- <EventData>
  <Data Name="SubjectUserSid">S-1-5-21-2216450734-2288107589-99135520-4696</Data>
  <Data Name="SubjectUserName">l1s\chunt</Data>
  <Data Name="SubjectDomainName">L1S</Data>
  <Data Name="FullyQualifiedSubjectUserName">l1s.loop1.com/MyBusiness/Users/SBSUsers/Core/Engineering/Field Engineering/Charles Hunt</Data>
  <Data Name="SubjectMachineSID">S-1-0-0</Data>
  <Data Name="SubjectMachineName">-</Data>
  <Data Name="FullyQualifiedSubjectMachineName">-</Data>
  <Data Name="MachineInventory">-</Data>
  <Data Name="CalledStationID">192.168.21.49</Data>
  <Data Name="CallingStationID">98.196.175.165</Data>
  <Data Name="NASIPv4Address">192.168.21.49</Data>
  <Data Name="NASIPv6Address">-</Data>
  <Data Name="NASIdentifier">L1SDC02</Data>
  <Data Name="NASPortType">Virtual</Data>
  <Data Name="NASPort">7</Data>
  <Data Name="ClientName">L1SDC02</Data>
  <Data Name="ClientIPAddress">192.168.21.49</Data>
  <Data Name="ProxyPolicyName">Microsoft Routing and Remote Access Service Policy</Data>
  <Data Name="NetworkPolicyName">Loop1 Corp</Data>
  <Data Name="AuthenticationProvider">Windows</Data>
  <Data Name="AuthenticationServer">L1SDC02.l1s.loop1.com</Data>
  <Data Name="AuthenticationType">EAP</Data>
  <Data Name="EAPType">Microsoft: Secured password (EAP-MSCHAP v2)</Data>
  <Data Name="AccountSessionIdentifier">353238</Data>
  <Data Name="QuarantineState">Full Access</Data>
  <Data Name="QuarantineSessionIdentifier">-</Data>
  <Data Name="LoggingResult">Accounting information was written to the local log file.</Data>
  </EventData>
  </Event>
```

**Comment by WallaceWilliam** [comment]
I tried to add for failure _(example from MSSQL)_


      <Group>
        <Source>RemoteAccess</Source>
        <Keywords>0x8000000000000000</Keywords>
        <Path>System</Path>
        <Expressions>
          <Expression>
            <XPath>//EventID</XPath>
            <Regex>^20271$</Regex>
          </Expression>
          <Expression>
            <XPath>(//Data)[2]</XPath>
            <Regex>
              <![CDATA[
                ^(?<username>.*)$
              ]]>
            </Regex>
          </Expression>
          <Expression>
            <XPath>(//Data)[3]</XPath>
            <Regex>
              <![CDATA[
                ^(?<ipaddress>.*)$
              ]]>
            </Regex>
          </Expression>
        </Expressions>
      </Group>


but it does not work

**Comment by jjxtra** [comment]
Please post the XML from event viewer, feel free to modify any sensitive data to be fake data.

**Comment by WallaceWilliam** [comment]
XML is the same as jjxtra

**Comment by jjxtra** [comment]
Not the config xml, the windows event viewer xml please

**Comment by WallaceWilliam** [comment]
I realized.
I say XML is the same as yours.
this is event System, not Application or Security

    <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
    <Provider Name="RemoteAccess" /> 
    <EventID Qualifiers="0">20271</EventID> 
    <Level>3</Level> 
    <Task>0</Task> 
    <Keywords>0x80000000000000</Keywords> 
    <TimeCreated SystemTime="2020-02-17T12:11:32.000000000Z" /> 
    <EventRecordID>473908</EventRecordID> 
    <Channel>System</Channel> 
    <Computer>dc0</Computer> 
    <Security /> 
    </System>
<EventData>
  <Data>{NA}</Data> 
  <Data>administrator</Data> 
  <Data>176.113.115.101</Data> 
  <Data>error message</Data> 
  <Data>0x10</Data> 
  <Binary>B3020000</Binary> 
  </EventData>
</Event>`

**Comment by WallaceWilliam** [comment]
<EventData>
    <Data>{NA}</Data> 
    <Data>administrator</Data> 
    <Data>176.113.115.101</Data> 
    <Data>error message.</Data> 
    <Data>0x10</Data> 
    <Binary>B3020000</Binary> 
    </EventData>
    </Event>

**Comment by atftb** [comment]
We're seeing the same issue.  Here's XML from the System log in Event Viewer:
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="RemoteAccess" /> 
  <EventID Qualifiers="0">20271</EventID> 
  <Level>3</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-03-23T19:40:08.225301000Z" /> 
  <EventRecordID>32407</EventRecordID> 
  <Channel>System</Channel> 
  <Computer>CITY-VPN16.cbj.local</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>{NA}</Data> 
  <Data>corinne</Data> 
  <Data>123.207.87.250</Data> 
  <Data>The remote connection was denied because the user name and password combination you provided is not recognized, or the selected authentication protocol is not permitted on the remote access server.</Data> 
  <Data>0x10</Data> 
  <Binary>B3020000</Binary> 
  </EventData>
  </Event>

Any progress on this?

**Comment by jjxtra** [comment]
I'll work on getting this added this week!

**Comment by jjxtra** [comment]
> 
> 
> We're seeing the same issue. Here's XML from the System log in Event Viewer:
> 20271 3 0 0x80000000000000 32407 System CITY-VPN16.cbj.local {NA} corinne 123.207.87.250 The remote connection was denied because the user name and password combination you provided is not recognized, or the selected authentication protocol is not permitted on the remote access server. 0x10 B3020000
> 
> Any progress on this?

Can you post the full raw XML?

**Comment by atftb** [comment]
I did originally.  If I click to edit my post the whole thing shows.  I think the xml and html of this page are at odds with each other.  I'll try it via uploading a file.  
[ipban.xml.txt](https://github.com/DigitalRuby/IPBan/files/4376867/ipban.xml.txt)

**Comment by jjxtra** [comment]
Thanks!

**Comment by jjxtra** [comment]
Had a few things pop up this week that limited my ability to work on things. Will take more stab at this on weekend or next week.

**Comment by atftb** [comment]
Any further progress on the RRAS issue?  Thanks...

**Comment by jjxtra** [comment]
Working on this today, will send update soon

**Comment by jjxtra** [comment]
This is now pushed to master branch, I will work on getting a new build

**Comment by jjxtra** [comment]
Released in v. 1.5.6 which is now out of beta.
