### ISSUE TITLE
Is it possible to block brute-force logins in IIS log files?

### ISSUE THREAD

**Issue by bcacbe** [DigitalRuby/IPBan#77]
Is it possible to block brute-force logins attempts against WordPress "wp-login.php" using the IIS log file?

**Comment by jjxtra** [comment]
Yes, just need to add a default log file path and some regex. Can you tell
me where these logs are by default and maybe send an example of some rows
from the file for both failed and success logins?

**Comment by bcacbe** [comment]
The path is the following format:

`E:\vhosts\domain.com\logs\iis\W3SVC559`

I was thinking the format could be changed to the following to work on multiple sites in IIS, if possible?

``E:/vhosts/*/logs/iis/*/*.log``

The IIS log looks like the following:

`2019-12-17 00:16:37 173.254.250.121 POST /wp-login.php - 80 - 114.34.74.142 HTTP/1.1 Mozilla/5.0+(Windows+NT+6.1;+rv:60.0)+Gecko/20100101+Firefox/60.0 http://domain.com/wp-login.php domain.com 200 0 0 12174 463 453`

`2019-12-17 00:16:42 173.254.250.121 POST /wp-login.php - 80 - 114.34.74.142 HTTP/1.1 Mozilla/5.0+(Windows+NT+6.1;+rv:60.0)+Gecko/20100101+Firefox/60.0 http://domain.com/wp-login.php domain.com 200 0 0 12174 490 421`
`

**Comment by bcacbe** [comment]
The successful login looks like the following:

`2019-12-17 23:02:41 W3SVC785 WIN-LHC53702N1H 173.254.250.121 GET /wp1234/wp-admin/ - 80 - 173.254.250.77 HTTP/1.1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/78.0.3904.108+Safari/537.36 wordpress_test_cookie=WP+Cookie+check - domain.net 302 0 0 704 502 93`

`2019-12-17 23:02:41 W3SVC785 WIN-LHC53702N1H 173.254.250.121 GET /wp1234/wp-login.php redirect_to=http%3A%2F%2Fdomain.net%2Fwp1234%2Fwp-admin%2F&reauth=1 80 - 173.254.250.77 HTTP/1.1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/78.0.3904.108+Safari/537.36 wordpress_test_cookie=WP+Cookie+check - domain.net 200 0 0 4148 582 78`

**Comment by jjxtra** [comment]
Log file locations:
```
D:\home\LogFiles\http\RawLogs
%SystemDrive%\inetpub\logs\LogFiles
```

**Comment by jjxtra** [comment]
Not sure on a direction here, going to close this for now until it can be given better thought.
