### ISSUE TITLE
about Windows Server 2008,2003 maybe can be throw by raw socket tcp/ip to Monitors?

### ISSUE THREAD

**Issue by sgf** [DigitalRuby/IPBan#80]
"Windows Server 2008 does a poor job of logging ip addresses and is end of life. "

Or
make an Privoxy on 3389 or user setting,modify the real port to another localloop port and then do check packets  the remote rdp IP address and RDP stauts;

**Comment by jjxtra** [comment]
I have no plans to do any work for any windows older than server 2012 and windows 7.

**Comment by sgf** [comment]
understand and accept,thank you reply.
anyway,your work is great!
