### ISSUE TITLE
How Can I Configure Regext for PostgreSQL for lock fails logon like MSSQL?

### ISSUE THREAD

**Issue by isaacsantamaria** [DigitalRuby/IPBan#81]
Hello!... Thanks for this program. Is really very good.

So, I was sawing how is possible make lock all failed logon in the PostgreSQL like MSSQL but I don't know how make with regex.

**Comment by jjxtra** [comment]
Please post xml log from event viewer or log file (with paths to file) with the failed logins. Feel free to mask out or change the ip addresses to dummy data.

**Comment by isaacsantamaria** [comment]
Thanks for you answer.

The below is the log in event viewer when the connection is received:
There are 2 logs lines

Line 1:

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="PostgreSQL" />
  <EventID Qualifiers="0">0</EventID>
  <Level>4</Level>
  <Task>0</Task>
  <Keywords>0x80000000000000</Keywords>
  <TimeCreated SystemTime="2020-01-26T09:49:25.000000000Z" />
  <EventRecordID>3649448</EventRecordID>
  <Channel>Application</Channel>
  <Computer>COMPUTER_NAME</Computer>
  <Security />
  </System>
- <EventData>
  <Data>2020-01-26 04:49:25 -05 LOG: conexión recibida: host=IP_ADDRESS port=59368</Data>
  </EventData>
  </Event>

Line 2:

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="PostgreSQL" />
  <EventID Qualifiers="0">0</EventID>
  <Level>4</Level>
  <Task>0</Task>
  <Keywords>0x80000000000000</Keywords>
  <TimeCreated SystemTime="2020-01-26T09:49:25.000000000Z" />
  <EventRecordID>3649449</EventRecordID>
  <Channel>Application</Channel>
  <Computer> COMPUTER_NAME </Computer>
  <Security />
  </System>
- <EventData>
  <Data>2020-01-26 04:49:25 -05 LOG: conexión autorizada: usuario=XXXX database=XXXX</Data>
  </EventData>
  </Event>
--
Isaac D. Santamaría F.
Cel Phone (Venezuela): (+58)-424-2594855<tel:+58%20424-2594855>
Skype: isaacsantamaria<tel:+58%20424-2594855>

**Comment by jjxtra** [comment]
Is there an event viewer entry with the ip address in it?

**Comment by jjxtra** [comment]
Well for some strange reason they put the user name in a separate log entry, seems a bit silly. But I will add something to the next update to capture the ip address from the first entry.

**Comment by isaacsantamaria** [comment]
Thanks for your kind attention!!!
