### ISSUE TITLE
The IPBAN service failed to start

### ISSUE THREAD

**Issue by SlavikCA** [DigitalRuby/IPBan#84]
**System:** Windows Server 2019 Standart

I configured IPBAN to start, as a service as Automation (Delayed Start).
Recently, I rebooted the server, and IPBAN service didn't start.

I found this in the Windows event logs:

> Feb 27, 2020 @ 18:30:05.059 | - | A timeout was reached (60000 milliseconds) while waiting for the IPBAN service to connect.
> Feb 27, 2020 @ 18:30:05.059 | - | The IPBAN service failed to start due to the following error:  The service did not respond to the start or control request in a timely fashion.

I only realized, that the service is not running today (March 1st) and started it manually. And it started without any problem.

Not sure, if it's important, but during the reboot, there was no Internet connection, as I was doing network maintenance. The LAN connection was up, but there was no Internet for a few hours.

And here is IPBAN own log (it only has entries up to the point of shutdown, nothing after reboot):
> 2020-02-27 15:23:31.3188|WARN|DigitalRuby.IPBanCore.Logger|Login failure: 163.172.52.206, , RDP, 1
> 2020-02-27 15:23:31.3188|WARN|DigitalRuby.IPBanCore.Logger|Login failure: 163.172.52.206, ADMINISTRATOR, RDP, 2
> 2020-02-27 15:23:31.3305|WARN|DigitalRuby.IPBanCore.Logger|Banning ip address: 163.172.52.206, user name: ADMINISTRATOR, config black listed: True, count: 2, extra info: 
> 2020-02-27 15:23:31.3725|WARN|DigitalRuby.IPBanCore.Logger|Updating firewall with 1 entries...
> 2020-02-27 18:26:21.2332|WARN|DigitalRuby.IPBanCore.Logger|Stopped IPBan service

**Comment by jjxtra** [comment]
Do you see any errors in the logfile.txt file in the ipban folder?

-- Jeff

**Comment by jjxtra** [comment]
Do you have failed event viewer logins after you successfully restarted the server?

**Comment by SlavikCA** [comment]
Timeline (All time in PST):
- Feb 27, 18:26: Server is shutting down for reboot
- Feb 27, 18:30: The server is booting. IPBAN fails to start (The service did not respond to the start or control request in a timely fashion)
- Feb 28, morning: Internet connection is restored
- Mar 1, evening: I realize, that there are a lot of failed RDP logins (>1000)
- Mar 1, 22:22: I manually start IPBAN

Failed logins between server restart (Feb 27, 18:26) and IPBAN start (Mar 1 22:54)
[Kibana 1](https://c2160591f0f041cb8869b6468f171c80.westus2.azure.elastic-cloud.com:9243/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-02-28T02:26:00.000Z',to:'2020-03-02T06:22:54.000Z'))&_a=(columns:!(message,source.ip),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'winlogbeat-*',key:host.name,negate:!f,params:(query:win19home),type:phrase),query:(match_phrase:(host.name:win19home)))),index:'winlogbeat-*',interval:auto,query:(language:kuery,query:'event.action%20:%22logon-failed%22%20'),sort:!(!('@timestamp',desc))))

If you want to look at all events, not just failed logins:
[Kibana 2](https://c2160591f0f041cb8869b6468f171c80.westus2.azure.elastic-cloud.com:9243/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-02-28T02:26:00.000Z',to:'2020-03-02T18:00:00.000Z'))&_a=(columns:!(message,source.ip),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'winlogbeat-*',key:host.name,negate:!f,params:(query:win19home),type:phrase),query:(match_phrase:(host.name:win19home)))),index:'winlogbeat-*',interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc))))

I do not see any failed logins after IPBAN service started on March 1.

I'll send creds for Kibana via email.

Also attaching IPBAN own complete logs for Feb 27 and March 1. There are no logs in between.

[logfile-mar-1.txt](https://github.com/DigitalRuby/IPBan/files/4277448/logfile-mar-1.txt)
[logfile-feb-27.txt](https://github.com/DigitalRuby/IPBan/files/4277449/logfile-feb-27.txt)

**Comment by jjxtra** [comment]
The Kibana logs clearly show a login failure, is there any chance you could get the raw xml from the Windows box itself with the failed login and paste it here? You can change any sensitive data to dummy data.

**Comment by SlavikCA** [comment]
Shared via email.

Also, totally random theory, feel free to ignore:
Can the service fail to start because it tries and fails to reach these endpoints during the service  start:
```
<add key="ExternalIPAddressUrl" value="https://checkip.amazonaws.com/"/>
<add key="FirewallUriSources" value="
         EmergingThreats,01:00:00:00,https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt
    "/>
```

**Comment by jjxtra** [comment]
Both calls are wrapped in try/catch blocks so it *shouldn't* be the cause.

-- Jeff

**Comment by jjxtra** [comment]
Sometimes the event viewer system or application logs can have some errors in them when services fail to start, do you see anything interesting in those event log categories?

**Comment by jjxtra** [comment]
As a test, I ran locally in debugger without network access of any kind (all adapters disabled) and there was no crash.

**Comment by SlavikCA** [comment]
I tried to look at the events right before and after IPBAN failed to start.
And I can't find anything, that stands out.

**Comment by jjxtra** [comment]
Can you post your exact Windows version including language?

**Comment by SlavikCA** [comment]
PS C:\Users\slavik> systeminfo /fo csv | ConvertFrom-Csv | select OS*, System* | Format-List

```
OS Name             : Microsoft Windows Server 2019 Standard
OS Version          : 10.0.17763 N/A Build 17763
OS Manufacturer     : Microsoft Corporation
OS Configuration    : Member Server
OS Build Type       : Multiprocessor Free
System Boot Time    : 2/27/2020, 6:26:46 PM
System Manufacturer : Dell Inc.
System Model        : Precision M4700
System Type         : x64-based PC
System Directory    : C:\Windows\system32
System Locale       : ru;Russian
```

**Comment by jjxtra** [comment]
Could be a language issue, would you be willing to try the same setup without Internet on a en-US install of server 2019?

**Comment by SlavikCA** [comment]
Just yesterday, I was installing windows updates. So, rebooted the server.
I also attempted to reboot without the Internet.

IPBAN started succesfully, no issues.

So, I must had some temporarily glitch. So, closing the issue.

Thank you again for the great product.
