### ISSUE TITLE
Regex optimization

### ISSUE THREAD

**Issue by alphanimal** [DigitalRuby/IPBan#87]
Hi!
In the default config there's a Log File check for `C:/Program Files/Microsoft/Exchange Server/*.log` using the regex `.*?,.*?,.*?,.*?,(?<ipaddress>.+?),(?<username>.+?),.*?AuthFailed`. This path mask matches over 28000 .log files on our system. About 1000 of them were changed in the last day.

I found that this is highly inefficient with lazy quantifiers `.*?,` to identity the CSV fields, because of all the backtracking the regex engine has to do.
It is far more efficient to use negated character classes like `[^,]*,`
So the better regex for this would be `[^,]*,[^,]*,[^,]*,[^,]*,(?<ipaddress>[^,]*),(?<username>[^,]*),[^,]*AuthFailed`

I tested a regex search in a text editor using both variants on about 1000 Exchange log files worth 500MB.

The default pattern using lazy quantifiers took about 5 hours and 20 minutes, throwing errors for many files along the way "Regex complexity too high searching file". The pattern using negated character classes took 1 minute 40 seconds for the same task.

There could even be more optimization done by excluding all the log files that have nothing to do with user authentication or introducing a new type to parse CSV without regex.

By the way, not all failed logins cause "AuthFailed" to be written. I found for example the SMTP service uses "LogonDenied" instead and the user name is contained in the following log entry

edit: regular-expressions.info even uses parsing CSV with lazy quantifier as an example of [Catastrophic Backtracking](https://www.regular-expressions.info/catastrophic.html) 😉

**Comment by jjxtra** [comment]
Awesome, I will update the regex. Thanks for sharing.

**Comment by alphanimal** [comment]
Thanks!

On the topic of regex, do you know if it's possible to match multiple lines? because in the SMTP log the IP address and user name are on seperate lines

```
2020-04-01T13:13:03.129Z,SRV-XCH03\External Authenticated Relay,08D7D4D2EFBC3E30,10,192.168.2.101:10587,92.118.38.34:46676,*,,Inbound AUTH LOGIN failed because of LogonDenied
2020-04-01T13:13:03.129Z,SRV-XCH03\External Authenticated Relay,08D7D4D2EFBC3E30,11,192.168.2.101:10587,92.118.38.34:46676,*,,User Name: shaun@example.com
```
I tried the following pattern, which matches in my text editor but doesn't seem to match in IPBan:
`^[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,(?<ipaddress>[^,]*),[^,]*,[^,]*,.*LogonDenied\n.*User Name: (?<username>.*)$`

**Comment by jjxtra** [comment]
I don't think this will be possible with the current code-base as I only
parse one line at a time from the log file.

-- Jeff

**Comment by jjxtra** [comment]
One option would be to check if the regex has a \n in it and then concat the next line, I will look into it...

**Comment by jjxtra** [comment]
Please check the last two commits in master, I have re-worked the regex, let me know what you think...

**Comment by alphanimal** [comment]
> One option would be to check if the regex has a \n in it and then concat the next line, I will look into it...

Or make a flag to select whether the regex should apply to each line or to the whole file. Then the default regex could have `^` and `$` included, and users can remove those if they want to match over multiple lines. Simply checking the pattern for `\n` seems shady.

I looked at those commits, seems fine to me! :) Surprisingly many places you fixed that.
Maybe if I find the time I'll go through all the Exchange server log files and make individual checks. In particular the SMTP is currently not working with the default config. Also Logons from OWA appear in a source named RDP. Thanks for your work! IPBan really is the best to keep out those brute force attacks.

**Comment by jjxtra** [comment]
Thanks for your wonderful feedback. Can you post some exchange server log file lines that are not working? You can mask ip and user name if you want. Same for OWA lines. I will get some unit tests made and a new version posted once I get those fixed.

**Comment by jjxtra** [comment]
Master branch has an option that looks for \n and will try the next line for a match. Are you able to build from source?

**Comment by alphanimal** [comment]
I was specifically working with the Frontend Transport logs in `C:\Program Files\Microsoft\Exchange Server\V15\TransportRoles\Logs\FrontEnd\ProtocolLog\SmtpReceive\*.LOG`
This folder contains hundreds of files with names like `RECV2020040208-1.LOG`
Next to SmtpReceive there's also a SmtpSend folder with logs in the same format, but I didn't find any authentication stuff in those. It might depend on your exchange server configuration and which Send/Receive connectors you have, so checking both folders is OK I think.

The SmtpReceive log contains this for a successful authentication:
```
2020-04-02T07:57:37.647Z,SRV-XCH03\External Authenticated Relay,08D7D4D2EFBC4CC6,15,192.168.0.101:10587,180.20.20.20:50767,*,user@example.com,authenticated
...
2020-04-02T07:57:37.708Z,SRV-XCH03\External Authenticated Relay,08D7D4D2EFBC4CC6,20,192.168.0.101:10587,180.20.20.20:50767,>,235 2.7.0 Authentication successful,
```
And this for unsuccessul authentication:
```
2020-04-02T08:31:07.381Z,SRV-XCH03\External Authenticated Relay,08D7D4D2EFBC4D65,15,192.168.0.101:10587,180.60.60.60:24175,*,,Inbound AUTH LOGIN failed because of LogonDenied
2020-04-02T08:31:07.381Z,SRV-XCH03\External Authenticated Relay,08D7D4D2EFBC4D65,16,192.168.0.101:10587,180.60.60.60:24175,*,,User Name: user@example.com
2020-04-02T08:31:07.381Z,SRV-XCH03\External Authenticated Relay,08D7D4D2EFBC4D65,17,192.168.0.101:10587,180.60.60.60:24175,*,Tarpit for '0.00:00:05' due to '535 5.7.3 Authentication unsuccessful',
2020-04-02T08:31:12.392Z,SRV-XCH03\External Authenticated Relay,08D7D4D2EFBC4D65,18,192.168.0.101:10587,180.60.60.60:24175,>,535 5.7.3 Authentication unsuccessful,
```

180.20.20.20 and 180.60.60.60 are example client IP addresses, user@example.com is the example user name

All the exchange server logs seem to be properly formatted CSV with header information. These have the following fields: date-time,connector-id,session-id,sequence-number,local-endpoint,remote-endpoint,event,data,context

Failed OWA authentication attempts come up on the Event Log check, but that's labelled "RDP" in the default config. Seems to be not only RDP!

I'm sorry i can't build from source. But I think the \n check is the wrong approach. What if there's more complex regex that looks for data from lines that are not adjacent? Maybe the client IP is only logged at the top and then a varying number of lines below there's the "auth failed" entry? what if multiple sessions are logged at the same time? the regex would have to correlate the session IDs to match the right IP with the right user etc. So I still think something like `<FailedLoginRegex multiline="true">` would be better. You should still be able to match the beginning and end of a line using `^` and `$`.

by the way is there an easy way to remove banned IPs without restarting the service and manually editing the database or firewall rules?

**Comment by jjxtra** [comment]
I will consider the multi-line thing. I still need some way to know from the regex how many lines to feed into the regex, so I will still likely scan the regex in some way to determine this.

Unfortunately ^...$ seems to only work once in a regex, so you have to use \n to match each end of line...

Let me know if I'm missing something, here's an example: https://regex101.com/r/1nIpQd/1

**Comment by alphanimal** [comment]
I don't know how exactly IPBan reads the logs right now. Would it be possible to simply take the text that is currently loaded line by line and just load it as a batch? So that would mean everything new since the last check.

I guess there could be timing problems, but if you do one check every few seconds (if there's new data) that should be fine? Worst case would be that the IP address comes first, then only after a long time the "auth failed" message comes on another line. That could actually be a way for an attacker to trick IPban, if the log is behaving that way. Also you'd have to make sure each batch contains only whole lines.

You can just use `\n` independently like `^line1\nline2$`. I use `^$` only to make sure it can't match part of a line.
Here it's working with my SMTP logs: https://regex101.com/r/r41Dg7/2
You could even make sure both lines belong to the same session using backreference: https://regex101.com/r/r41Dg7/3
It gets more complicated when there are a variable amount of lines between the IP and the "auth failed" message, but regex can do a lot. Thankfully most logs write the client IP on the same line.
You wouldn't be able to check this hypothetical log if you can't search multiple lines for example: https://regex101.com/r/bNCKsO/1

**Comment by jjxtra** [comment]
Right now the file is passed line-by-line, but I am re-thinking this whether I can pass the entire string blob. I might be able to, with some re-work of how I parse the regex in order to handle multiple matches. Will keep you posted. Thanks for sharing the logs, I will get some tests added!

**Comment by alphanimal** [comment]
Awesome! Yes, you'd need to handle multiple matches in a batch. But also I think the batches should be aligned with the line start/end

**Comment by jjxtra** [comment]
Yup!

-- Jeff

**Comment by jjxtra** [comment]
Please see the latest commit and let me know what you think. I am now looping all the matches in the regex on all the new text from the log file, which is guaranteed to be up to and including the end of the last full line of text.

**Comment by alphanimal** [comment]
Seems fine! If you release a build I can test it

**Comment by jjxtra** [comment]
Please try https://github.com/DigitalRuby/IPBan/releases/tag/1.5.5 and let me know how it goes!

**Comment by jjxtra** [comment]
Can you post the raw XML from a failed OWA attempt from event viewer? I want to see if there's anything possible to differentiate from RDP...

**Comment by alphanimal** [comment]
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-A5BA-3E3B0328C30D}" /> 
    <EventID>4625</EventID> 
    <Version>0</Version> 
    <Level>0</Level> 
    <Task>12544</Task> 
    <Opcode>0</Opcode> 
    <Keywords>0x8010000000000000</Keywords> 
    <TimeCreated SystemTime="2020-04-05T19:12:41.597844900Z" /> 
    <EventRecordID>295694367</EventRecordID> 
    <Correlation ActivityID="{9EF3A62A-06BB-0005-46A6-F39EBB06D601}" /> 
    <Execution ProcessID="728" ThreadID="18912" /> 
    <Channel>Security</Channel> 
    <Computer>srv-xch03.example.com</Computer> 
    <Security /> 
  </System>
  <EventData>
    <Data Name="SubjectUserSid">S-1-5-18</Data> 
    <Data Name="SubjectUserName">SRV-XCH03$</Data> 
    <Data Name="SubjectDomainName">EXAMPLE</Data> 
    <Data Name="SubjectLogonId">0x3e7</Data> 
    <Data Name="TargetUserSid">S-1-0-0</Data> 
    <Data Name="TargetUserName">testuser</Data> 
    <Data Name="TargetDomainName">example.com</Data> 
    <Data Name="Status">0xc000006d</Data> 
    <Data Name="FailureReason">%%2313</Data> 
    <Data Name="SubStatus">0xc0000064</Data> 
    <Data Name="LogonType">8</Data> 
    <Data Name="LogonProcessName">Advapi</Data> 
    <Data Name="AuthenticationPackageName">Negotiate</Data> 
    <Data Name="WorkstationName">SRV-XCH03</Data> 
    <Data Name="TransmittedServices">-</Data> 
    <Data Name="LmPackageName">-</Data> 
    <Data Name="KeyLength">0</Data> 
    <Data Name="ProcessId">0x23b0</Data> 
    <Data Name="ProcessName">C:\Windows\System32\inetsrv\w3wp.exe</Data> 
    <Data Name="IpAddress">80.200.100.100</Data> 
    <Data Name="IpPort">1765</Data> 
  </EventData>
</Event>
```

You can at least see the authentication comes from IIS (w3wp.exe)
I couldn't find any corresponding log entries in other sources or files.

**Comment by alphanimal** [comment]
This is the XML from an actual RDP login attempt. ProcessName is just "-":
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-A5BA-3E3B0328C30D}" />
    <EventID>4625</EventID>
    <Version>0</Version>
    <Level>0</Level>
    <Task>12544</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8010000000000000</Keywords>
    <TimeCreated SystemTime="2020-04-05T19:32:57.732138700Z" />
    <EventRecordID>295695996</EventRecordID>
    <Correlation ActivityID="{9EF3A62A-06BB-0005-46A6-F39EBB06D601}" />
    <Execution ProcessID="728" ThreadID="2116" />
    <Channel>Security</Channel>
    <Computer>srv-xch03.example.com</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="SubjectUserSid">S-1-0-0</Data>
    <Data Name="SubjectUserName">-</Data>
    <Data Name="SubjectDomainName">-</Data>
    <Data Name="SubjectLogonId">0x0</Data>
    <Data Name="TargetUserSid">S-1-0-0</Data>
    <Data Name="TargetUserName">rdpuser</Data>
    <Data Name="TargetDomainName">USERDOMAIN</Data>
    <Data Name="Status">0xc000006d</Data>
    <Data Name="FailureReason">%%2313</Data>
    <Data Name="SubStatus">0xc0000064</Data>
    <Data Name="LogonType">3</Data>
    <Data Name="LogonProcessName">NtLmSsp </Data>
    <Data Name="AuthenticationPackageName">NTLM</Data>
    <Data Name="WorkstationName">CLIENT-PC</Data>
    <Data Name="TransmittedServices">-</Data>
    <Data Name="LmPackageName">-</Data>
    <Data Name="KeyLength">0</Data>
    <Data Name="ProcessId">0x0</Data>
    <Data Name="ProcessName">-</Data>
    <Data Name="IpAddress">192.168.210.180</Data>
    <Data Name="IpPort">0</Data>
  </EventData>
</Event>
```

**Comment by jjxtra** [comment]
I've been reading about backtracking and it seems from everything I read that `.*?` ir more performant than `.*`. What are your thoughts?

**Comment by alphanimal** [comment]
I just read that article again: https://www.regular-expressions.info/catastrophic.html

It seems the problem is not actually with the lazy quantifiers. You can do the same thing that was in your original regex using `.*` instead of `.*?` but it will still be inefficient, as there are multiple ways to match. [This](https://regex101.com/r/R1GH3n/1) will have the same result as [this](https://regex101.com/r/R1GH3n/2) when the CSV is properly formatted. (Also be aware that in CSV there might be escaped `,` inside a field like `a,b,"c,d",e`)

**Comment by alphanimal** [comment]
I found regex101 has this debug mode where you can go through each step in the regex engine. Look at this: https://regex101.com/r/R1GH3n/2/debugger trying to find the 8th field which doesn't exist

**Comment by jjxtra** [comment]
Sweet that is super handy. How is the 1.5.5 beta working for you?

**Comment by alphanimal** [comment]
> Please try https://github.com/DigitalRuby/IPBan/releases/tag/1.5.5 and let me know how it goes!

Sorry I missed this. Will try soon

**Comment by alphanimal** [comment]
Hello!

There's another problem with multi-line matching: `[^,]` will also match CR and LF characters, so if you want to match things only within a single line, you will have to use `[^,\r\n]` everywhere. This is also faster because it doesn't backtrack across multiple lines. I uüdated my SMTP log pattern and also reintroduced lazy quantifiers again for performance :)

`^(?:[^,\r\n]*,){5}(?<ipaddress>[^,\r\n]*),(?:[^,\r\n]*,){2}[^,\n\r]*?LogonDenied\n[^\r\n]*?User Name: (?<username>[^\r\n]+)$`

Here's an example where the old pattern goes wrong: https://regex101.com/r/azbQPS/2

Also here's a better (multiline compatible) version of the original Exchange log check: `^(?:[^,\r\n]*,){4}(?<ipaddress>[^,\r\n]*),(?<username>[^,\r\n]*),.*?AuthFailed.*$`

Given how complex this multiline-regex is becoming, I would prefer if the default way would still be matching single lines. It would avoid performance problems where catastrophic backtracking occurs over multiple lines. Multi-line matching should only be used when necessary, like my SMTP logs.

Other than that, the 1.5.5 beta seems to work fine now.

**Comment by jjxtra** [comment]
I strip out all \r so you don't have to mess with those. I will get the regex's updated.

**Comment by jjxtra** [comment]
I'm going to go ahead and close this, please post back if you see any additional issues.

**Comment by jjxtra** [comment]
Re-opening waiting for log file you are seeing with missed entries

**Comment by jjxtra** [comment]
Just FYI I am writing integration tests off of your last smtp log files posted in this issue. I have them passing and the failed login file has two failed logins and the success file one succesful login. Is that what you expect?

**Comment by alphanimal** [comment]
Yes

**Comment by jjxtra** [comment]
Ok good. Feel free to email me or post here the bigger versions of you log files and I will add them to the integration test. Let me know your expected fail/success count, and of course feel free to change all the user names and ip, etc. to dummy data.

**Comment by jjxtra** [comment]
I updated the 1.5.5 pre-release with a fix to the regex for single-line exchange failed logins.

**Comment by jjxtra** [comment]
Allright, 1.5.5 is out of beta, let me know if you see any more issues with performance.

**Comment by Indigo744** [comment]
Hello all,

I'm sorry to re-open this thread, but I have a question regarding one of the change you introduced:
The `PathAndMask` value for MSExchange rule was changed from 
```
C:/Program Files/Microsoft/Exchange Server/*.log
```
to 
```
C:/Program Files/Microsoft/Exchange Server/V15/TransportRoles/Logs/FrontEnd/ProtocolLog/**.log
```

I guess `V15` means **Exchange 2013**, because we have **Exchange 2010** and I only have a `V14`  folder. 

However, I the subfolder only goes to `C:/Program Files/Microsoft/Exchange Server/V14/TransportRoles/Logs/`. I can't see any `FrontEnd` folder.

Does it means there is no possibility for IPBan to work with Exchange 2010?
What would be needed in order to make it work on it? Do I need to activate something to have logging functionality?

Thank you!

**Comment by jjxtra** [comment]
I've updated the path in the default config file to use a `*` for the version. You'll need to find wherever your smtp log files are in your exchange version and change the config file to that path.

**Comment by alphanimal** [comment]
In my experience most of the failed logins on Exchange get picked up by the Windows event log checks. The log files only showed SMTP auth attempts for me, where the client IP was missing in the event log.

**Comment by Indigo744** [comment]
@alphanimal I guess you are right. I tried to fail some login (OWA, SMTP Auth...) and they all went into the Windows event log. I couldn't find anything in the text logs regarding these attempts.
So I guess I won't miss much by not monitoring these logs.

@jjxtra it would be great to have a table somewhere showing exactly what is monitored and how (i.e. which rule), and maybe the corresponding OS version compatibility.

**Comment by jjxtra** [comment]
I will try to add something to the wiki with the defaults at some point, for now the DigitalRuby.IPBan.dll.config file will get you everything, although you have to parse it out in your brain :)

**Comment by jjxtra** [comment]
This is very exciting for ipban as .net 5 comes this fall, regex performance will be even better:

https://devblogs.microsoft.com/dotnet/regex-performance-improvements-in-net-5/
