### ISSUE TITLE
Count reset after "Login succeeded"

### ISSUE THREAD

**Issue by davidmartinez-servinformatica** [DigitalRuby/IPBan#88]
Can you add a flag to activate a count reset after a "Login succeded"?

I prefeer not reset any counter in time, but set it to 0, after a successful login.

**Comment by jjxtra** [comment]
Sure I will look into this!

**Comment by jjxtra** [comment]
To confirm, if a success login is detected, remove all failed logins in the ipban sqlite db for that ip address?

**Comment by thidiniz** [comment]
> To confirm, if a success login is detected, remove all failed logins from memory and in the ipban sqlite db for that ip address?

Yes, I'd like that too.. I`ve set failed login attemps to 3, and sometimes you mistype something, or forget that keyboard is in lower/upper case and ending up blocking yourself.

thanks for this awesome tool

**Comment by davidmartinez-servinformatica** [comment]
> To confirm, if a success login is detected, remove all failed logins from memory and in the ipban sqlite db for that ip address?

Yes.

**Comment by ndroftheline** [comment]
but what if a script kiddie (or, more likely, a vengeful ex) actaully successfully guesses one of your users' passwords? wouldn't this behaviour then remove all trace of the attempts, and their originating IP addresses?

**Comment by davidmartinez-servinformatica** [comment]
I have low number of failed attempts (5), so if users failed a couple of times, and have several users from the same office (with dinamic ip), it results in a ban.
I try teach my server clients good practices, and don't let him store password for login, but nomal people are some piece of dumb.

**Comment by davidmartinez-servinformatica** [comment]
I think that I don't explained well.

If a hacker gains access to a server, the number of failed logins dosn't matter cause he have access.
I set a very low number of failure attemps, so in a small office conection to server, maybe 10 users for example, if user 1 and 2 fail 2 times to log-in on server, the next failed login will block all office.
That I only want is if I have a succesful login from one IP, clear the failed login attemps count from this IP. 

I purpose you put a flag, to activate this feature, making this usable for who wants.

Thanks for all anyway.

**Comment by jjxtra** [comment]
I will look into a config option

**Comment by davidmartinez-servinformatica** [comment]
here is an example what I mean:
`2020-06-12 08:00:56.8452|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: XX.136.45.27, user name: g.marin, source: RDP
2020-06-12 08:02:27.0959|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: XX.136.45.27, user name: k.garcia, source: RDP
2020-06-12 08:04:12.3624|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: XX.136.45.27, user name: p.montero, source: RDP
2020-06-12 08:07:12.8383|WARN|DigitalRuby.IPBanCore.Logger|Login succeeded, address: XX.136.45.27, user name: a.sanchez, source: RDP
2020-06-12 08:10:58.4024|WARN|DigitalRuby.IPBanCore.Logger|Login failure: XX.136.45.27, l.linan, RDP, 5
2020-06-12 08:10:58.4033|WARN|DigitalRuby.IPBanCore.Logger|Banning ip address: XX.136.45.27, user name: l.linan, config black listed: False, count: 5, extra info: 
2020-06-12 08:10:58.4033|WARN|DigitalRuby.IPBanCore.Logger|Login failure: XX.136.45.27, , RDP, 5
2020-06-12 08:10:58.4033|WARN|DigitalRuby.IPBanCore.Logger|IP XX.136.45.27, , RDP ban pending.
2020-06-12 08:10:58.4454|WARN|DigitalRuby.IPBanCore.Logger|Updating firewall with 1 entries...`

After a lot of succesfully log-ins, some user fail her 5 attempt in last 24h so block IP for all her office. Surely someone fail 4 attempts yesterday, buy if he had a reset count after he grant accees, today her coworkerd didn't block all her office.

**Comment by jjxtra** [comment]
Latest master branch has an option now, called `ClearFailedLoginsOnSuccessfulLogin`
