### ISSUE TITLE
make it even more obvious for noobs like me how to get basic confirmation that it's working

### ISSUE THREAD

**Issue by ndroftheline** [DigitalRuby/IPBan#90]
Jeff! This project is amazing and I'm very glad you're taking it Pro, looking forward to that. 

In the meanwhile, just a gentle suggestion: make it even more painfully obvious to noobs like me how to get active confirmation that IPBan is doing its thing post install. I couldn't find anything in the wiki or other documentation I found saying "just open logfile.txt in the ipban program directory to see all the fools getting banned" . Maybe I missed it - but that may mean it's insufficiently obvious.

**Comment by jjxtra** [comment]
I will add something to that effect :)

**Comment by jjxtra** [comment]
Added to FAQ in the wiki
