### ISSUE TITLE
digitalruby.ipban.dll is detected a malware Gen:Illusion.ML.Skyline.B.1010101

### ISSUE THREAD

**Issue by gustavorlopez** [DigitalRuby/IPBan#92]
Hi,
digitalruby.ipban.dll is detected by BitDefender EndPoint Security Elite as malware: Gen:Illusion.ML.Skyline.B.1010101

![image](https://user-images.githubusercontent.com/1809845/82767314-590ba700-9dec-11ea-8f2a-0c46a2f80c95.png)

**Comment by gustavorlopez** [comment]
Version: 1.5.6 Beta 1

**Comment by gustavorlopez** [comment]
VirusTotal info:
https://www.virustotal.com/gui/file/75cf50f03e6bc1a40ba8bf5196374ef4dfc65f11007ea305cc2e4c70c2354b8c/detection

**Comment by jjxtra** [comment]
No idea why this is cropping up. I do a lot with the firewall, com interop and event viewer. But easiest solution is to build and run the code yourself if you have any worries.
