### ISSUE TITLE
Dns whitelisting not working

### ISSUE THREAD

**Issue by jjxtra** [DigitalRuby/IPBan#99]
A user reported that adding a dns entry to the whitelist is not working, an ip address in the `A`  records for the dns was still banned. Investigate and add a unit test.

**Comment by markmetroit** [comment]
Hi Jeff, I have emailed you further info on this issue

**Comment by jjxtra** [comment]
Thanks, I have a TODO: to write better tests against dns whitelisting.

**Comment by jjxtra** [comment]
I added more dns tests will create a new release soon-ish
